
// This file has been generated by the GUI designer. Do not modify.
namespace Zyrenth.ZoraGen.GtkUI
{
	public partial class NewMainWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Zyrenth.ZoraGen.GtkUI.NewMainWindow
			this.Name = "Zyrenth.ZoraGen.GtkUI.NewMainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("NewMainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
