
// This file has been generated by the GUI designer. Do not modify.
namespace Zyrenth.ZoraGen.GtkUI
{
	public partial class DecoderForm
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Table table3;

		private global::Gtk.Button btnBack;

		private global::Gtk.Button btnReset;

		private global::Zyrenth.ZoraGen.GtkUI.LargeSecretWidget secretwidget1;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.Table table1;

		private global::Gtk.Button btnSymbol1;

		private global::Gtk.Image image3;

		private global::Gtk.Button btnSymbol10;

		private global::Gtk.Image image13;

		private global::Gtk.Button btnSymbol11;

		private global::Gtk.Image image14;

		private global::Gtk.Button btnSymbol12;

		private global::Gtk.Image image15;

		private global::Gtk.Button btnSymbol13;

		private global::Gtk.Image image16;

		private global::Gtk.Button btnSymbol14;

		private global::Gtk.Image image17;

		private global::Gtk.Button btnSymbol15;

		private global::Gtk.Image image4;

		private global::Gtk.Button btnSymbol16;

		private global::Gtk.Image image18;

		private global::Gtk.Button btnSymbol17;

		private global::Gtk.Image image19;

		private global::Gtk.Button btnSymbol18;

		private global::Gtk.Image image20;

		private global::Gtk.Button btnSymbol19;

		private global::Gtk.Image image21;

		private global::Gtk.Button btnSymbol2;

		private global::Gtk.Image image5;

		private global::Gtk.Button btnSymbol20;

		private global::Gtk.Image image23;

		private global::Gtk.Button btnSymbol21;

		private global::Gtk.Image image22;

		private global::Gtk.Button btnSymbol22;

		private global::Gtk.Image image24;

		private global::Gtk.Button btnSymbol23;

		private global::Gtk.Image image25;

		private global::Gtk.Button btnSymbol24;

		private global::Gtk.Image image26;

		private global::Gtk.Button btnSymbol25;

		private global::Gtk.Image image27;

		private global::Gtk.Button btnSymbol26;

		private global::Gtk.Image image28;

		private global::Gtk.Button btnSymbol27;

		private global::Gtk.Image image29;

		private global::Gtk.Button btnSymbol28;

		private global::Gtk.Image image30;

		private global::Gtk.Button btnSymbol29;

		private global::Gtk.Image image31;

		private global::Gtk.Button btnSymbol3;

		private global::Gtk.Image image6;

		private global::Gtk.Button btnSymbol30;

		private global::Gtk.Image image32;

		private global::Gtk.Button btnSymbol31;

		private global::Gtk.Image image33;

		private global::Gtk.Button btnSymbol32;

		private global::Gtk.Image image34;

		private global::Gtk.Button btnSymbol33;

		private global::Gtk.Image image35;

		private global::Gtk.Button btnSymbol34;

		private global::Gtk.Image image37;

		private global::Gtk.Button btnSymbol35;

		private global::Gtk.Image image38;

		private global::Gtk.Button btnSymbol36;

		private global::Gtk.Image image39;

		private global::Gtk.Button btnSymbol37;

		private global::Gtk.Image image40;

		private global::Gtk.Button btnSymbol38;

		private global::Gtk.Image image41;

		private global::Gtk.Button btnSymbol39;

		private global::Gtk.Image image42;

		private global::Gtk.Button btnSymbol4;

		private global::Gtk.Image image7;

		private global::Gtk.Button btnSymbol40;

		private global::Gtk.Image image43;

		private global::Gtk.Button btnSymbol41;

		private global::Gtk.Image image44;

		private global::Gtk.Button btnSymbol42;

		private global::Gtk.Image image45;

		private global::Gtk.Button btnSymbol43;

		private global::Gtk.Image image46;

		private global::Gtk.Button btnSymbol44;

		private global::Gtk.Image image47;

		private global::Gtk.Button btnSymbol45;

		private global::Gtk.Image image48;

		private global::Gtk.Button btnSymbol46;

		private global::Gtk.Image image49;

		private global::Gtk.Button btnSymbol47;

		private global::Gtk.Image image50;

		private global::Gtk.Button btnSymbol48;

		private global::Gtk.Image image51;

		private global::Gtk.Button btnSymbol49;

		private global::Gtk.Image image52;

		private global::Gtk.Button btnSymbol5;

		private global::Gtk.Image image8;

		private global::Gtk.Button btnSymbol50;

		private global::Gtk.Image image53;

		private global::Gtk.Button btnSymbol51;

		private global::Gtk.Image image54;

		private global::Gtk.Button btnSymbol52;

		private global::Gtk.Image image55;

		private global::Gtk.Button btnSymbol53;

		private global::Gtk.Image image56;

		private global::Gtk.Button btnSymbol54;

		private global::Gtk.Image image57;

		private global::Gtk.Button btnSymbol55;

		private global::Gtk.Image image58;

		private global::Gtk.Button btnSymbol56;

		private global::Gtk.Image image59;

		private global::Gtk.Button btnSymbol57;

		private global::Gtk.Image image60;

		private global::Gtk.Button btnSymbol58;

		private global::Gtk.Image image61;

		private global::Gtk.Button btnSymbol59;

		private global::Gtk.Image image62;

		private global::Gtk.Button btnSymbol6;

		private global::Gtk.Image image9;

		private global::Gtk.Button btnSymbol60;

		private global::Gtk.Image image63;

		private global::Gtk.Button btnSymbol61;

		private global::Gtk.Image image64;

		private global::Gtk.Button btnSymbol62;

		private global::Gtk.Image image65;

		private global::Gtk.Button btnSymbol63;

		private global::Gtk.Image image66;

		private global::Gtk.Button btnSymbol64;

		private global::Gtk.Image image67;

		private global::Gtk.Button btnSymbol7;

		private global::Gtk.Image image10;

		private global::Gtk.Button btnSymbol8;

		private global::Gtk.Image image11;

		private global::Gtk.Button btnSymbol9;

		private global::Gtk.Image image12;

		private global::Gtk.Label label5;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Entry txtSymbols;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label6;

		private global::Gtk.HBox hbox2;

		private global::Gtk.CheckButton chkAppendRings;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Zyrenth.ZoraGen.GtkUI.DecoderForm
			this.Name = "Zyrenth.ZoraGen.GtkUI.DecoderForm";
			this.Title = global::Mono.Unix.Catalog.GetString("Decode Secret");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Farore.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child Zyrenth.ZoraGen.GtkUI.DecoderForm.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			// Container child table3.Gtk.Table+TableChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("Back");
			this.table3.Add(this.btnBack);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.btnBack]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XPadding = ((uint)(5));
			w2.YPadding = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.btnReset = new global::Gtk.Button();
			this.btnReset.CanFocus = true;
			this.btnReset.Name = "btnReset";
			this.btnReset.UseUnderline = true;
			this.btnReset.Label = global::Mono.Unix.Catalog.GetString("Reset");
			this.table3.Add(this.btnReset);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.btnReset]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XPadding = ((uint)(5));
			w3.YPadding = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.secretwidget1 = new global::Zyrenth.ZoraGen.GtkUI.LargeSecretWidget();
			this.secretwidget1.WidthRequest = 172;
			this.secretwidget1.HeightRequest = 52;
			this.secretwidget1.Events = ((global::Gdk.EventMask)(256));
			this.secretwidget1.Name = "secretwidget1";
			this.table3.Add(this.secretwidget1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.secretwidget1]));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add(this.table3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(13)), false);
			this.table1.Name = "table1";
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol1 = new global::Gtk.Button();
			this.btnSymbol1.CanFocus = true;
			this.btnSymbol1.Name = "btnSymbol1";
			// Container child btnSymbol1.Gtk.Container+ContainerChild
			this.image3 = new global::Gtk.Image();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.00.png");
			this.btnSymbol1.Add(this.image3);
			this.table1.Add(this.btnSymbol1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol1]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol10 = new global::Gtk.Button();
			this.btnSymbol10.CanFocus = true;
			this.btnSymbol10.Name = "btnSymbol10";
			// Container child btnSymbol10.Gtk.Container+ContainerChild
			this.image13 = new global::Gtk.Image();
			this.image13.Name = "image13";
			this.image13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.09.png");
			this.btnSymbol10.Add(this.image13);
			this.table1.Add(this.btnSymbol10);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol10]));
			w9.LeftAttach = ((uint)(9));
			w9.RightAttach = ((uint)(10));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol11 = new global::Gtk.Button();
			this.btnSymbol11.CanFocus = true;
			this.btnSymbol11.Name = "btnSymbol11";
			// Container child btnSymbol11.Gtk.Container+ContainerChild
			this.image14 = new global::Gtk.Image();
			this.image14.Name = "image14";
			this.image14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.10.png");
			this.btnSymbol11.Add(this.image14);
			this.table1.Add(this.btnSymbol11);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol11]));
			w11.LeftAttach = ((uint)(10));
			w11.RightAttach = ((uint)(11));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol12 = new global::Gtk.Button();
			this.btnSymbol12.CanFocus = true;
			this.btnSymbol12.Name = "btnSymbol12";
			// Container child btnSymbol12.Gtk.Container+ContainerChild
			this.image15 = new global::Gtk.Image();
			this.image15.Name = "image15";
			this.image15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.11.png");
			this.btnSymbol12.Add(this.image15);
			this.table1.Add(this.btnSymbol12);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol12]));
			w13.LeftAttach = ((uint)(11));
			w13.RightAttach = ((uint)(12));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol13 = new global::Gtk.Button();
			this.btnSymbol13.CanFocus = true;
			this.btnSymbol13.Name = "btnSymbol13";
			// Container child btnSymbol13.Gtk.Container+ContainerChild
			this.image16 = new global::Gtk.Image();
			this.image16.Name = "image16";
			this.image16.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.12.png");
			this.btnSymbol13.Add(this.image16);
			this.table1.Add(this.btnSymbol13);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol13]));
			w15.LeftAttach = ((uint)(12));
			w15.RightAttach = ((uint)(13));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol14 = new global::Gtk.Button();
			this.btnSymbol14.CanFocus = true;
			this.btnSymbol14.Name = "btnSymbol14";
			// Container child btnSymbol14.Gtk.Container+ContainerChild
			this.image17 = new global::Gtk.Image();
			this.image17.Name = "image17";
			this.image17.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.13.png");
			this.btnSymbol14.Add(this.image17);
			this.table1.Add(this.btnSymbol14);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol14]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol15 = new global::Gtk.Button();
			this.btnSymbol15.CanFocus = true;
			this.btnSymbol15.Name = "btnSymbol15";
			// Container child btnSymbol15.Gtk.Container+ContainerChild
			this.image4 = new global::Gtk.Image();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.14.png");
			this.btnSymbol15.Add(this.image4);
			this.table1.Add(this.btnSymbol15);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol15]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol16 = new global::Gtk.Button();
			this.btnSymbol16.CanFocus = true;
			this.btnSymbol16.Name = "btnSymbol16";
			// Container child btnSymbol16.Gtk.Container+ContainerChild
			this.image18 = new global::Gtk.Image();
			this.image18.Name = "image18";
			this.image18.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.15.png");
			this.btnSymbol16.Add(this.image18);
			this.table1.Add(this.btnSymbol16);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol16]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol17 = new global::Gtk.Button();
			this.btnSymbol17.CanFocus = true;
			this.btnSymbol17.Name = "btnSymbol17";
			// Container child btnSymbol17.Gtk.Container+ContainerChild
			this.image19 = new global::Gtk.Image();
			this.image19.Name = "image19";
			this.image19.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.16.png");
			this.btnSymbol17.Add(this.image19);
			this.table1.Add(this.btnSymbol17);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol17]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(3));
			w23.RightAttach = ((uint)(4));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol18 = new global::Gtk.Button();
			this.btnSymbol18.CanFocus = true;
			this.btnSymbol18.Name = "btnSymbol18";
			// Container child btnSymbol18.Gtk.Container+ContainerChild
			this.image20 = new global::Gtk.Image();
			this.image20.Name = "image20";
			this.image20.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.17.png");
			this.btnSymbol18.Add(this.image20);
			this.table1.Add(this.btnSymbol18);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol18]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(4));
			w25.RightAttach = ((uint)(5));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol19 = new global::Gtk.Button();
			this.btnSymbol19.CanFocus = true;
			this.btnSymbol19.Name = "btnSymbol19";
			// Container child btnSymbol19.Gtk.Container+ContainerChild
			this.image21 = new global::Gtk.Image();
			this.image21.Name = "image21";
			this.image21.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.18.png");
			this.btnSymbol19.Add(this.image21);
			this.table1.Add(this.btnSymbol19);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol19]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.LeftAttach = ((uint)(5));
			w27.RightAttach = ((uint)(6));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol2 = new global::Gtk.Button();
			this.btnSymbol2.CanFocus = true;
			this.btnSymbol2.Name = "btnSymbol2";
			// Container child btnSymbol2.Gtk.Container+ContainerChild
			this.image5 = new global::Gtk.Image();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.01.png");
			this.btnSymbol2.Add(this.image5);
			this.table1.Add(this.btnSymbol2);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol2]));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol20 = new global::Gtk.Button();
			this.btnSymbol20.CanFocus = true;
			this.btnSymbol20.Name = "btnSymbol20";
			// Container child btnSymbol20.Gtk.Container+ContainerChild
			this.image23 = new global::Gtk.Image();
			this.image23.Name = "image23";
			this.image23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.19.png");
			this.btnSymbol20.Add(this.image23);
			this.table1.Add(this.btnSymbol20);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol20]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.LeftAttach = ((uint)(6));
			w31.RightAttach = ((uint)(7));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol21 = new global::Gtk.Button();
			this.btnSymbol21.CanFocus = true;
			this.btnSymbol21.Name = "btnSymbol21";
			// Container child btnSymbol21.Gtk.Container+ContainerChild
			this.image22 = new global::Gtk.Image();
			this.image22.Name = "image22";
			this.image22.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.20.png");
			this.btnSymbol21.Add(this.image22);
			this.table1.Add(this.btnSymbol21);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol21]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.LeftAttach = ((uint)(7));
			w33.RightAttach = ((uint)(8));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol22 = new global::Gtk.Button();
			this.btnSymbol22.CanFocus = true;
			this.btnSymbol22.Name = "btnSymbol22";
			// Container child btnSymbol22.Gtk.Container+ContainerChild
			this.image24 = new global::Gtk.Image();
			this.image24.Name = "image24";
			this.image24.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.21.png");
			this.btnSymbol22.Add(this.image24);
			this.table1.Add(this.btnSymbol22);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol22]));
			w35.TopAttach = ((uint)(1));
			w35.BottomAttach = ((uint)(2));
			w35.LeftAttach = ((uint)(8));
			w35.RightAttach = ((uint)(9));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol23 = new global::Gtk.Button();
			this.btnSymbol23.CanFocus = true;
			this.btnSymbol23.Name = "btnSymbol23";
			// Container child btnSymbol23.Gtk.Container+ContainerChild
			this.image25 = new global::Gtk.Image();
			this.image25.Name = "image25";
			this.image25.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.22.png");
			this.btnSymbol23.Add(this.image25);
			this.table1.Add(this.btnSymbol23);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol23]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.LeftAttach = ((uint)(9));
			w37.RightAttach = ((uint)(10));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol24 = new global::Gtk.Button();
			this.btnSymbol24.CanFocus = true;
			this.btnSymbol24.Name = "btnSymbol24";
			// Container child btnSymbol24.Gtk.Container+ContainerChild
			this.image26 = new global::Gtk.Image();
			this.image26.Name = "image26";
			this.image26.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.23.png");
			this.btnSymbol24.Add(this.image26);
			this.table1.Add(this.btnSymbol24);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol24]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(10));
			w39.RightAttach = ((uint)(11));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol25 = new global::Gtk.Button();
			this.btnSymbol25.CanFocus = true;
			this.btnSymbol25.Name = "btnSymbol25";
			// Container child btnSymbol25.Gtk.Container+ContainerChild
			this.image27 = new global::Gtk.Image();
			this.image27.Name = "image27";
			this.image27.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.24.png");
			this.btnSymbol25.Add(this.image27);
			this.table1.Add(this.btnSymbol25);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol25]));
			w41.TopAttach = ((uint)(1));
			w41.BottomAttach = ((uint)(2));
			w41.LeftAttach = ((uint)(11));
			w41.RightAttach = ((uint)(12));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol26 = new global::Gtk.Button();
			this.btnSymbol26.CanFocus = true;
			this.btnSymbol26.Name = "btnSymbol26";
			// Container child btnSymbol26.Gtk.Container+ContainerChild
			this.image28 = new global::Gtk.Image();
			this.image28.Name = "image28";
			this.image28.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.25.png");
			this.btnSymbol26.Add(this.image28);
			this.table1.Add(this.btnSymbol26);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol26]));
			w43.TopAttach = ((uint)(1));
			w43.BottomAttach = ((uint)(2));
			w43.LeftAttach = ((uint)(12));
			w43.RightAttach = ((uint)(13));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol27 = new global::Gtk.Button();
			this.btnSymbol27.CanFocus = true;
			this.btnSymbol27.Name = "btnSymbol27";
			// Container child btnSymbol27.Gtk.Container+ContainerChild
			this.image29 = new global::Gtk.Image();
			this.image29.Name = "image29";
			this.image29.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.26.png");
			this.btnSymbol27.Add(this.image29);
			this.table1.Add(this.btnSymbol27);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol27]));
			w45.TopAttach = ((uint)(2));
			w45.BottomAttach = ((uint)(3));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol28 = new global::Gtk.Button();
			this.btnSymbol28.CanFocus = true;
			this.btnSymbol28.Name = "btnSymbol28";
			// Container child btnSymbol28.Gtk.Container+ContainerChild
			this.image30 = new global::Gtk.Image();
			this.image30.Name = "image30";
			this.image30.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.27.png");
			this.btnSymbol28.Add(this.image30);
			this.table1.Add(this.btnSymbol28);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol28]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol29 = new global::Gtk.Button();
			this.btnSymbol29.CanFocus = true;
			this.btnSymbol29.Name = "btnSymbol29";
			// Container child btnSymbol29.Gtk.Container+ContainerChild
			this.image31 = new global::Gtk.Image();
			this.image31.Name = "image31";
			this.image31.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.28.png");
			this.btnSymbol29.Add(this.image31);
			this.table1.Add(this.btnSymbol29);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol29]));
			w49.TopAttach = ((uint)(2));
			w49.BottomAttach = ((uint)(3));
			w49.LeftAttach = ((uint)(2));
			w49.RightAttach = ((uint)(3));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol3 = new global::Gtk.Button();
			this.btnSymbol3.CanFocus = true;
			this.btnSymbol3.Name = "btnSymbol3";
			// Container child btnSymbol3.Gtk.Container+ContainerChild
			this.image6 = new global::Gtk.Image();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.02.png");
			this.btnSymbol3.Add(this.image6);
			this.table1.Add(this.btnSymbol3);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol3]));
			w51.LeftAttach = ((uint)(2));
			w51.RightAttach = ((uint)(3));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol30 = new global::Gtk.Button();
			this.btnSymbol30.CanFocus = true;
			this.btnSymbol30.Name = "btnSymbol30";
			// Container child btnSymbol30.Gtk.Container+ContainerChild
			this.image32 = new global::Gtk.Image();
			this.image32.Name = "image32";
			this.image32.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.29.png");
			this.btnSymbol30.Add(this.image32);
			this.table1.Add(this.btnSymbol30);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol30]));
			w53.TopAttach = ((uint)(2));
			w53.BottomAttach = ((uint)(3));
			w53.LeftAttach = ((uint)(3));
			w53.RightAttach = ((uint)(4));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol31 = new global::Gtk.Button();
			this.btnSymbol31.CanFocus = true;
			this.btnSymbol31.Name = "btnSymbol31";
			// Container child btnSymbol31.Gtk.Container+ContainerChild
			this.image33 = new global::Gtk.Image();
			this.image33.Name = "image33";
			this.image33.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.30.png");
			this.btnSymbol31.Add(this.image33);
			this.table1.Add(this.btnSymbol31);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol31]));
			w55.TopAttach = ((uint)(2));
			w55.BottomAttach = ((uint)(3));
			w55.LeftAttach = ((uint)(4));
			w55.RightAttach = ((uint)(5));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol32 = new global::Gtk.Button();
			this.btnSymbol32.CanFocus = true;
			this.btnSymbol32.Name = "btnSymbol32";
			// Container child btnSymbol32.Gtk.Container+ContainerChild
			this.image34 = new global::Gtk.Image();
			this.image34.Name = "image34";
			this.image34.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.31.png");
			this.btnSymbol32.Add(this.image34);
			this.table1.Add(this.btnSymbol32);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol32]));
			w57.TopAttach = ((uint)(2));
			w57.BottomAttach = ((uint)(3));
			w57.LeftAttach = ((uint)(5));
			w57.RightAttach = ((uint)(6));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol33 = new global::Gtk.Button();
			this.btnSymbol33.CanFocus = true;
			this.btnSymbol33.Name = "btnSymbol33";
			// Container child btnSymbol33.Gtk.Container+ContainerChild
			this.image35 = new global::Gtk.Image();
			this.image35.Name = "image35";
			this.image35.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.32.png");
			this.btnSymbol33.Add(this.image35);
			this.table1.Add(this.btnSymbol33);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol33]));
			w59.TopAttach = ((uint)(2));
			w59.BottomAttach = ((uint)(3));
			w59.LeftAttach = ((uint)(7));
			w59.RightAttach = ((uint)(8));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol34 = new global::Gtk.Button();
			this.btnSymbol34.CanFocus = true;
			this.btnSymbol34.Name = "btnSymbol34";
			// Container child btnSymbol34.Gtk.Container+ContainerChild
			this.image37 = new global::Gtk.Image();
			this.image37.Name = "image37";
			this.image37.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.33.png");
			this.btnSymbol34.Add(this.image37);
			this.table1.Add(this.btnSymbol34);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol34]));
			w61.TopAttach = ((uint)(2));
			w61.BottomAttach = ((uint)(3));
			w61.LeftAttach = ((uint)(8));
			w61.RightAttach = ((uint)(9));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol35 = new global::Gtk.Button();
			this.btnSymbol35.CanFocus = true;
			this.btnSymbol35.Name = "btnSymbol35";
			// Container child btnSymbol35.Gtk.Container+ContainerChild
			this.image38 = new global::Gtk.Image();
			this.image38.Name = "image38";
			this.image38.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.34.png");
			this.btnSymbol35.Add(this.image38);
			this.table1.Add(this.btnSymbol35);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol35]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.LeftAttach = ((uint)(9));
			w63.RightAttach = ((uint)(10));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol36 = new global::Gtk.Button();
			this.btnSymbol36.CanFocus = true;
			this.btnSymbol36.Name = "btnSymbol36";
			// Container child btnSymbol36.Gtk.Container+ContainerChild
			this.image39 = new global::Gtk.Image();
			this.image39.Name = "image39";
			this.image39.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.35.png");
			this.btnSymbol36.Add(this.image39);
			this.table1.Add(this.btnSymbol36);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol36]));
			w65.TopAttach = ((uint)(2));
			w65.BottomAttach = ((uint)(3));
			w65.LeftAttach = ((uint)(10));
			w65.RightAttach = ((uint)(11));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol37 = new global::Gtk.Button();
			this.btnSymbol37.CanFocus = true;
			this.btnSymbol37.Name = "btnSymbol37";
			// Container child btnSymbol37.Gtk.Container+ContainerChild
			this.image40 = new global::Gtk.Image();
			this.image40.Name = "image40";
			this.image40.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.36.png");
			this.btnSymbol37.Add(this.image40);
			this.table1.Add(this.btnSymbol37);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol37]));
			w67.TopAttach = ((uint)(2));
			w67.BottomAttach = ((uint)(3));
			w67.LeftAttach = ((uint)(11));
			w67.RightAttach = ((uint)(12));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol38 = new global::Gtk.Button();
			this.btnSymbol38.CanFocus = true;
			this.btnSymbol38.Name = "btnSymbol38";
			// Container child btnSymbol38.Gtk.Container+ContainerChild
			this.image41 = new global::Gtk.Image();
			this.image41.Name = "image41";
			this.image41.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.37.png");
			this.btnSymbol38.Add(this.image41);
			this.table1.Add(this.btnSymbol38);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol38]));
			w69.TopAttach = ((uint)(2));
			w69.BottomAttach = ((uint)(3));
			w69.LeftAttach = ((uint)(12));
			w69.RightAttach = ((uint)(13));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol39 = new global::Gtk.Button();
			this.btnSymbol39.CanFocus = true;
			this.btnSymbol39.Name = "btnSymbol39";
			// Container child btnSymbol39.Gtk.Container+ContainerChild
			this.image42 = new global::Gtk.Image();
			this.image42.Name = "image42";
			this.image42.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.38.png");
			this.btnSymbol39.Add(this.image42);
			this.table1.Add(this.btnSymbol39);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol39]));
			w71.TopAttach = ((uint)(3));
			w71.BottomAttach = ((uint)(4));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol4 = new global::Gtk.Button();
			this.btnSymbol4.CanFocus = true;
			this.btnSymbol4.Name = "btnSymbol4";
			// Container child btnSymbol4.Gtk.Container+ContainerChild
			this.image7 = new global::Gtk.Image();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.03.png");
			this.btnSymbol4.Add(this.image7);
			this.table1.Add(this.btnSymbol4);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol4]));
			w73.LeftAttach = ((uint)(3));
			w73.RightAttach = ((uint)(4));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol40 = new global::Gtk.Button();
			this.btnSymbol40.CanFocus = true;
			this.btnSymbol40.Name = "btnSymbol40";
			// Container child btnSymbol40.Gtk.Container+ContainerChild
			this.image43 = new global::Gtk.Image();
			this.image43.Name = "image43";
			this.image43.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.39.png");
			this.btnSymbol40.Add(this.image43);
			this.table1.Add(this.btnSymbol40);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol40]));
			w75.TopAttach = ((uint)(3));
			w75.BottomAttach = ((uint)(4));
			w75.LeftAttach = ((uint)(1));
			w75.RightAttach = ((uint)(2));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol41 = new global::Gtk.Button();
			this.btnSymbol41.CanFocus = true;
			this.btnSymbol41.Name = "btnSymbol41";
			// Container child btnSymbol41.Gtk.Container+ContainerChild
			this.image44 = new global::Gtk.Image();
			this.image44.Name = "image44";
			this.image44.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.40.png");
			this.btnSymbol41.Add(this.image44);
			this.table1.Add(this.btnSymbol41);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol41]));
			w77.TopAttach = ((uint)(3));
			w77.BottomAttach = ((uint)(4));
			w77.LeftAttach = ((uint)(2));
			w77.RightAttach = ((uint)(3));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol42 = new global::Gtk.Button();
			this.btnSymbol42.CanFocus = true;
			this.btnSymbol42.Name = "btnSymbol42";
			// Container child btnSymbol42.Gtk.Container+ContainerChild
			this.image45 = new global::Gtk.Image();
			this.image45.Name = "image45";
			this.image45.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.41.png");
			this.btnSymbol42.Add(this.image45);
			this.table1.Add(this.btnSymbol42);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol42]));
			w79.TopAttach = ((uint)(3));
			w79.BottomAttach = ((uint)(4));
			w79.LeftAttach = ((uint)(3));
			w79.RightAttach = ((uint)(4));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol43 = new global::Gtk.Button();
			this.btnSymbol43.CanFocus = true;
			this.btnSymbol43.Name = "btnSymbol43";
			// Container child btnSymbol43.Gtk.Container+ContainerChild
			this.image46 = new global::Gtk.Image();
			this.image46.Name = "image46";
			this.image46.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.42.png");
			this.btnSymbol43.Add(this.image46);
			this.table1.Add(this.btnSymbol43);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol43]));
			w81.TopAttach = ((uint)(3));
			w81.BottomAttach = ((uint)(4));
			w81.LeftAttach = ((uint)(4));
			w81.RightAttach = ((uint)(5));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol44 = new global::Gtk.Button();
			this.btnSymbol44.CanFocus = true;
			this.btnSymbol44.Name = "btnSymbol44";
			// Container child btnSymbol44.Gtk.Container+ContainerChild
			this.image47 = new global::Gtk.Image();
			this.image47.Name = "image47";
			this.image47.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.43.png");
			this.btnSymbol44.Add(this.image47);
			this.table1.Add(this.btnSymbol44);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol44]));
			w83.TopAttach = ((uint)(3));
			w83.BottomAttach = ((uint)(4));
			w83.LeftAttach = ((uint)(5));
			w83.RightAttach = ((uint)(6));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol45 = new global::Gtk.Button();
			this.btnSymbol45.CanFocus = true;
			this.btnSymbol45.Name = "btnSymbol45";
			// Container child btnSymbol45.Gtk.Container+ContainerChild
			this.image48 = new global::Gtk.Image();
			this.image48.Name = "image48";
			this.image48.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.44.png");
			this.btnSymbol45.Add(this.image48);
			this.table1.Add(this.btnSymbol45);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol45]));
			w85.TopAttach = ((uint)(3));
			w85.BottomAttach = ((uint)(4));
			w85.LeftAttach = ((uint)(6));
			w85.RightAttach = ((uint)(7));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol46 = new global::Gtk.Button();
			this.btnSymbol46.CanFocus = true;
			this.btnSymbol46.Name = "btnSymbol46";
			// Container child btnSymbol46.Gtk.Container+ContainerChild
			this.image49 = new global::Gtk.Image();
			this.image49.Name = "image49";
			this.image49.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.45.png");
			this.btnSymbol46.Add(this.image49);
			this.table1.Add(this.btnSymbol46);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol46]));
			w87.TopAttach = ((uint)(3));
			w87.BottomAttach = ((uint)(4));
			w87.LeftAttach = ((uint)(7));
			w87.RightAttach = ((uint)(8));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol47 = new global::Gtk.Button();
			this.btnSymbol47.CanFocus = true;
			this.btnSymbol47.Name = "btnSymbol47";
			// Container child btnSymbol47.Gtk.Container+ContainerChild
			this.image50 = new global::Gtk.Image();
			this.image50.Name = "image50";
			this.image50.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.46.png");
			this.btnSymbol47.Add(this.image50);
			this.table1.Add(this.btnSymbol47);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol47]));
			w89.TopAttach = ((uint)(3));
			w89.BottomAttach = ((uint)(4));
			w89.LeftAttach = ((uint)(8));
			w89.RightAttach = ((uint)(9));
			w89.XOptions = ((global::Gtk.AttachOptions)(4));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol48 = new global::Gtk.Button();
			this.btnSymbol48.CanFocus = true;
			this.btnSymbol48.Name = "btnSymbol48";
			// Container child btnSymbol48.Gtk.Container+ContainerChild
			this.image51 = new global::Gtk.Image();
			this.image51.Name = "image51";
			this.image51.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.47.png");
			this.btnSymbol48.Add(this.image51);
			this.table1.Add(this.btnSymbol48);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol48]));
			w91.TopAttach = ((uint)(3));
			w91.BottomAttach = ((uint)(4));
			w91.LeftAttach = ((uint)(9));
			w91.RightAttach = ((uint)(10));
			w91.XOptions = ((global::Gtk.AttachOptions)(4));
			w91.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol49 = new global::Gtk.Button();
			this.btnSymbol49.CanFocus = true;
			this.btnSymbol49.Name = "btnSymbol49";
			// Container child btnSymbol49.Gtk.Container+ContainerChild
			this.image52 = new global::Gtk.Image();
			this.image52.Name = "image52";
			this.image52.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.48.png");
			this.btnSymbol49.Add(this.image52);
			this.table1.Add(this.btnSymbol49);
			global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol49]));
			w93.TopAttach = ((uint)(3));
			w93.BottomAttach = ((uint)(4));
			w93.LeftAttach = ((uint)(10));
			w93.RightAttach = ((uint)(11));
			w93.XOptions = ((global::Gtk.AttachOptions)(4));
			w93.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol5 = new global::Gtk.Button();
			this.btnSymbol5.CanFocus = true;
			this.btnSymbol5.Name = "btnSymbol5";
			// Container child btnSymbol5.Gtk.Container+ContainerChild
			this.image8 = new global::Gtk.Image();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.04.png");
			this.btnSymbol5.Add(this.image8);
			this.table1.Add(this.btnSymbol5);
			global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol5]));
			w95.LeftAttach = ((uint)(4));
			w95.RightAttach = ((uint)(5));
			w95.XOptions = ((global::Gtk.AttachOptions)(4));
			w95.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol50 = new global::Gtk.Button();
			this.btnSymbol50.CanFocus = true;
			this.btnSymbol50.Name = "btnSymbol50";
			// Container child btnSymbol50.Gtk.Container+ContainerChild
			this.image53 = new global::Gtk.Image();
			this.image53.Name = "image53";
			this.image53.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.49.png");
			this.btnSymbol50.Add(this.image53);
			this.table1.Add(this.btnSymbol50);
			global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol50]));
			w97.TopAttach = ((uint)(3));
			w97.BottomAttach = ((uint)(4));
			w97.LeftAttach = ((uint)(11));
			w97.RightAttach = ((uint)(12));
			w97.XOptions = ((global::Gtk.AttachOptions)(4));
			w97.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol51 = new global::Gtk.Button();
			this.btnSymbol51.CanFocus = true;
			this.btnSymbol51.Name = "btnSymbol51";
			// Container child btnSymbol51.Gtk.Container+ContainerChild
			this.image54 = new global::Gtk.Image();
			this.image54.Name = "image54";
			this.image54.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.50.png");
			this.btnSymbol51.Add(this.image54);
			this.table1.Add(this.btnSymbol51);
			global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol51]));
			w99.TopAttach = ((uint)(3));
			w99.BottomAttach = ((uint)(4));
			w99.LeftAttach = ((uint)(12));
			w99.RightAttach = ((uint)(13));
			w99.XOptions = ((global::Gtk.AttachOptions)(4));
			w99.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol52 = new global::Gtk.Button();
			this.btnSymbol52.CanFocus = true;
			this.btnSymbol52.Name = "btnSymbol52";
			// Container child btnSymbol52.Gtk.Container+ContainerChild
			this.image55 = new global::Gtk.Image();
			this.image55.Name = "image55";
			this.image55.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.51.png");
			this.btnSymbol52.Add(this.image55);
			this.table1.Add(this.btnSymbol52);
			global::Gtk.Table.TableChild w101 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol52]));
			w101.TopAttach = ((uint)(4));
			w101.BottomAttach = ((uint)(5));
			w101.XOptions = ((global::Gtk.AttachOptions)(4));
			w101.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol53 = new global::Gtk.Button();
			this.btnSymbol53.CanFocus = true;
			this.btnSymbol53.Name = "btnSymbol53";
			// Container child btnSymbol53.Gtk.Container+ContainerChild
			this.image56 = new global::Gtk.Image();
			this.image56.Name = "image56";
			this.image56.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.52.png");
			this.btnSymbol53.Add(this.image56);
			this.table1.Add(this.btnSymbol53);
			global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol53]));
			w103.TopAttach = ((uint)(4));
			w103.BottomAttach = ((uint)(5));
			w103.LeftAttach = ((uint)(1));
			w103.RightAttach = ((uint)(2));
			w103.XOptions = ((global::Gtk.AttachOptions)(4));
			w103.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol54 = new global::Gtk.Button();
			this.btnSymbol54.CanFocus = true;
			this.btnSymbol54.Name = "btnSymbol54";
			// Container child btnSymbol54.Gtk.Container+ContainerChild
			this.image57 = new global::Gtk.Image();
			this.image57.Name = "image57";
			this.image57.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.53.png");
			this.btnSymbol54.Add(this.image57);
			this.table1.Add(this.btnSymbol54);
			global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol54]));
			w105.TopAttach = ((uint)(4));
			w105.BottomAttach = ((uint)(5));
			w105.LeftAttach = ((uint)(2));
			w105.RightAttach = ((uint)(3));
			w105.XOptions = ((global::Gtk.AttachOptions)(4));
			w105.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol55 = new global::Gtk.Button();
			this.btnSymbol55.CanFocus = true;
			this.btnSymbol55.Name = "btnSymbol55";
			// Container child btnSymbol55.Gtk.Container+ContainerChild
			this.image58 = new global::Gtk.Image();
			this.image58.Name = "image58";
			this.image58.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.54.png");
			this.btnSymbol55.Add(this.image58);
			this.table1.Add(this.btnSymbol55);
			global::Gtk.Table.TableChild w107 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol55]));
			w107.TopAttach = ((uint)(4));
			w107.BottomAttach = ((uint)(5));
			w107.LeftAttach = ((uint)(3));
			w107.RightAttach = ((uint)(4));
			w107.XOptions = ((global::Gtk.AttachOptions)(4));
			w107.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol56 = new global::Gtk.Button();
			this.btnSymbol56.CanFocus = true;
			this.btnSymbol56.Name = "btnSymbol56";
			// Container child btnSymbol56.Gtk.Container+ContainerChild
			this.image59 = new global::Gtk.Image();
			this.image59.Name = "image59";
			this.image59.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.55.png");
			this.btnSymbol56.Add(this.image59);
			this.table1.Add(this.btnSymbol56);
			global::Gtk.Table.TableChild w109 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol56]));
			w109.TopAttach = ((uint)(4));
			w109.BottomAttach = ((uint)(5));
			w109.LeftAttach = ((uint)(4));
			w109.RightAttach = ((uint)(5));
			w109.XOptions = ((global::Gtk.AttachOptions)(4));
			w109.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol57 = new global::Gtk.Button();
			this.btnSymbol57.CanFocus = true;
			this.btnSymbol57.Name = "btnSymbol57";
			// Container child btnSymbol57.Gtk.Container+ContainerChild
			this.image60 = new global::Gtk.Image();
			this.image60.Name = "image60";
			this.image60.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.56.png");
			this.btnSymbol57.Add(this.image60);
			this.table1.Add(this.btnSymbol57);
			global::Gtk.Table.TableChild w111 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol57]));
			w111.TopAttach = ((uint)(4));
			w111.BottomAttach = ((uint)(5));
			w111.LeftAttach = ((uint)(5));
			w111.RightAttach = ((uint)(6));
			w111.XOptions = ((global::Gtk.AttachOptions)(4));
			w111.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol58 = new global::Gtk.Button();
			this.btnSymbol58.CanFocus = true;
			this.btnSymbol58.Name = "btnSymbol58";
			// Container child btnSymbol58.Gtk.Container+ContainerChild
			this.image61 = new global::Gtk.Image();
			this.image61.Name = "image61";
			this.image61.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.57.png");
			this.btnSymbol58.Add(this.image61);
			this.table1.Add(this.btnSymbol58);
			global::Gtk.Table.TableChild w113 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol58]));
			w113.TopAttach = ((uint)(4));
			w113.BottomAttach = ((uint)(5));
			w113.LeftAttach = ((uint)(6));
			w113.RightAttach = ((uint)(7));
			w113.XOptions = ((global::Gtk.AttachOptions)(4));
			w113.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol59 = new global::Gtk.Button();
			this.btnSymbol59.CanFocus = true;
			this.btnSymbol59.Name = "btnSymbol59";
			// Container child btnSymbol59.Gtk.Container+ContainerChild
			this.image62 = new global::Gtk.Image();
			this.image62.Name = "image62";
			this.image62.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.58.png");
			this.btnSymbol59.Add(this.image62);
			this.table1.Add(this.btnSymbol59);
			global::Gtk.Table.TableChild w115 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol59]));
			w115.TopAttach = ((uint)(4));
			w115.BottomAttach = ((uint)(5));
			w115.LeftAttach = ((uint)(7));
			w115.RightAttach = ((uint)(8));
			w115.XOptions = ((global::Gtk.AttachOptions)(4));
			w115.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol6 = new global::Gtk.Button();
			this.btnSymbol6.CanFocus = true;
			this.btnSymbol6.Name = "btnSymbol6";
			// Container child btnSymbol6.Gtk.Container+ContainerChild
			this.image9 = new global::Gtk.Image();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.05.png");
			this.btnSymbol6.Add(this.image9);
			this.table1.Add(this.btnSymbol6);
			global::Gtk.Table.TableChild w117 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol6]));
			w117.LeftAttach = ((uint)(5));
			w117.RightAttach = ((uint)(6));
			w117.XOptions = ((global::Gtk.AttachOptions)(4));
			w117.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol60 = new global::Gtk.Button();
			this.btnSymbol60.CanFocus = true;
			this.btnSymbol60.Name = "btnSymbol60";
			// Container child btnSymbol60.Gtk.Container+ContainerChild
			this.image63 = new global::Gtk.Image();
			this.image63.Name = "image63";
			this.image63.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.59.png");
			this.btnSymbol60.Add(this.image63);
			this.table1.Add(this.btnSymbol60);
			global::Gtk.Table.TableChild w119 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol60]));
			w119.TopAttach = ((uint)(4));
			w119.BottomAttach = ((uint)(5));
			w119.LeftAttach = ((uint)(8));
			w119.RightAttach = ((uint)(9));
			w119.XOptions = ((global::Gtk.AttachOptions)(4));
			w119.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol61 = new global::Gtk.Button();
			this.btnSymbol61.CanFocus = true;
			this.btnSymbol61.Name = "btnSymbol61";
			// Container child btnSymbol61.Gtk.Container+ContainerChild
			this.image64 = new global::Gtk.Image();
			this.image64.Name = "image64";
			this.image64.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.60.png");
			this.btnSymbol61.Add(this.image64);
			this.table1.Add(this.btnSymbol61);
			global::Gtk.Table.TableChild w121 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol61]));
			w121.TopAttach = ((uint)(4));
			w121.BottomAttach = ((uint)(5));
			w121.LeftAttach = ((uint)(9));
			w121.RightAttach = ((uint)(10));
			w121.XOptions = ((global::Gtk.AttachOptions)(4));
			w121.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol62 = new global::Gtk.Button();
			this.btnSymbol62.CanFocus = true;
			this.btnSymbol62.Name = "btnSymbol62";
			// Container child btnSymbol62.Gtk.Container+ContainerChild
			this.image65 = new global::Gtk.Image();
			this.image65.Name = "image65";
			this.image65.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.61.png");
			this.btnSymbol62.Add(this.image65);
			this.table1.Add(this.btnSymbol62);
			global::Gtk.Table.TableChild w123 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol62]));
			w123.TopAttach = ((uint)(4));
			w123.BottomAttach = ((uint)(5));
			w123.LeftAttach = ((uint)(10));
			w123.RightAttach = ((uint)(11));
			w123.XOptions = ((global::Gtk.AttachOptions)(4));
			w123.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol63 = new global::Gtk.Button();
			this.btnSymbol63.CanFocus = true;
			this.btnSymbol63.Name = "btnSymbol63";
			// Container child btnSymbol63.Gtk.Container+ContainerChild
			this.image66 = new global::Gtk.Image();
			this.image66.Name = "image66";
			this.image66.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.62.png");
			this.btnSymbol63.Add(this.image66);
			this.table1.Add(this.btnSymbol63);
			global::Gtk.Table.TableChild w125 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol63]));
			w125.TopAttach = ((uint)(4));
			w125.BottomAttach = ((uint)(5));
			w125.LeftAttach = ((uint)(11));
			w125.RightAttach = ((uint)(12));
			w125.XOptions = ((global::Gtk.AttachOptions)(4));
			w125.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol64 = new global::Gtk.Button();
			this.btnSymbol64.CanFocus = true;
			this.btnSymbol64.Name = "btnSymbol64";
			// Container child btnSymbol64.Gtk.Container+ContainerChild
			this.image67 = new global::Gtk.Image();
			this.image67.Name = "image67";
			this.image67.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.63.png");
			this.btnSymbol64.Add(this.image67);
			this.table1.Add(this.btnSymbol64);
			global::Gtk.Table.TableChild w127 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol64]));
			w127.TopAttach = ((uint)(4));
			w127.BottomAttach = ((uint)(5));
			w127.LeftAttach = ((uint)(12));
			w127.RightAttach = ((uint)(13));
			w127.XOptions = ((global::Gtk.AttachOptions)(4));
			w127.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol7 = new global::Gtk.Button();
			this.btnSymbol7.CanFocus = true;
			this.btnSymbol7.Name = "btnSymbol7";
			// Container child btnSymbol7.Gtk.Container+ContainerChild
			this.image10 = new global::Gtk.Image();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.06.png");
			this.btnSymbol7.Add(this.image10);
			this.table1.Add(this.btnSymbol7);
			global::Gtk.Table.TableChild w129 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol7]));
			w129.LeftAttach = ((uint)(6));
			w129.RightAttach = ((uint)(7));
			w129.XOptions = ((global::Gtk.AttachOptions)(4));
			w129.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol8 = new global::Gtk.Button();
			this.btnSymbol8.CanFocus = true;
			this.btnSymbol8.Name = "btnSymbol8";
			// Container child btnSymbol8.Gtk.Container+ContainerChild
			this.image11 = new global::Gtk.Image();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.07.png");
			this.btnSymbol8.Add(this.image11);
			this.table1.Add(this.btnSymbol8);
			global::Gtk.Table.TableChild w131 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol8]));
			w131.LeftAttach = ((uint)(7));
			w131.RightAttach = ((uint)(8));
			w131.XOptions = ((global::Gtk.AttachOptions)(4));
			w131.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSymbol9 = new global::Gtk.Button();
			this.btnSymbol9.CanFocus = true;
			this.btnSymbol9.Name = "btnSymbol9";
			// Container child btnSymbol9.Gtk.Container+ContainerChild
			this.image12 = new global::Gtk.Image();
			this.image12.Name = "image12";
			this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Zyrenth.ZoraGen.GtkUI.Images.Symbols.08.png");
			this.btnSymbol9.Add(this.image12);
			this.table1.Add(this.btnSymbol9);
			global::Gtk.Table.TableChild w133 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSymbol9]));
			w133.LeftAttach = ((uint)(8));
			w133.RightAttach = ((uint)(9));
			w133.XOptions = ((global::Gtk.AttachOptions)(4));
			w133.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add(this.table1);
			// Notebook tab
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Symbol Keyboard");
			this.notebook1.SetTabLabel(this.table1, this.label5);
			this.label5.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtSymbols = new global::Gtk.Entry();
			this.txtSymbols.CanFocus = true;
			this.txtSymbols.Name = "txtSymbols";
			this.txtSymbols.IsEditable = true;
			this.txtSymbols.InvisibleChar = '●';
			this.vbox3.Add(this.txtSymbols);
			global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.txtSymbols]));
			w135.Position = 0;
			w135.Expand = false;
			w135.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Secrets can be entered in any mix of following formats:");
			this.label7.Wrap = true;
			this.vbox3.Add(this.label7);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label7]));
			w136.Position = 1;
			w136.Expand = false;
			w136.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xpad = 10;
			this.label8.Xalign = 0F;
			this.label8.LabelProp = "→N♥Nh\nright N heart N h\n{right}N{heart}Nh\nRigHtN ♥N  h";
			this.vbox3.Add(this.label8);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label8]));
			w137.Position = 2;
			w137.Expand = false;
			w137.Fill = false;
			this.notebook1.Add(this.vbox3);
			global::Gtk.Notebook.NotebookChild w138 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox3]));
			w138.Position = 1;
			// Notebook tab
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Text Entry");
			this.notebook1.SetTabLabel(this.vbox3, this.label6);
			this.label6.ShowAll();
			this.vbox1.Add(this.notebook1);
			global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
			w139.Position = 1;
			w139.Expand = false;
			w139.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.chkAppendRings = new global::Gtk.CheckButton();
			this.chkAppendRings.CanFocus = true;
			this.chkAppendRings.Name = "chkAppendRings";
			this.chkAppendRings.Label = global::Mono.Unix.Catalog.GetString("Add to Existing Rings");
			this.chkAppendRings.DrawIndicator = true;
			this.chkAppendRings.UseUnderline = true;
			this.hbox2.Add(this.chkAppendRings);
			global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.chkAppendRings]));
			w140.Position = 0;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w141.Position = 2;
			w141.Expand = false;
			w141.Fill = false;
			w1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(w1[this.vbox1]));
			w142.Position = 0;
			// Internal child Zyrenth.ZoraGen.GtkUI.DecoderForm.ActionArea
			global::Gtk.HButtonBox w143 = this.ActionArea;
			w143.Name = "dialog1_ActionArea";
			w143.Spacing = 10;
			w143.BorderWidth = ((uint)(5));
			w143.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w144 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w143[this.buttonCancel]));
			w144.Expand = false;
			w144.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w145 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w143[this.buttonOk]));
			w145.Position = 1;
			w145.Expand = false;
			w145.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 430;
			this.DefaultHeight = 367;
			this.Show();
			this.btnReset.Clicked += new global::System.EventHandler(this.OnBtnResetClicked);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
			this.notebook1.SwitchPage += new global::Gtk.SwitchPageHandler(this.OnNotebook1SwitchPage);
			this.btnSymbol9.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol8.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol7.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol64.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol63.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol62.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol61.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol60.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol6.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol59.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol58.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol57.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol56.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol55.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol54.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol53.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol52.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol51.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol50.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol5.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol49.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol48.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol47.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol46.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol45.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol44.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol43.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol42.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol41.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol40.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol4.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol39.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol38.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol37.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol36.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol35.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol34.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol33.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol32.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol31.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol30.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol3.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol29.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol28.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol27.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol26.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol25.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol24.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol23.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol22.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol21.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol20.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol2.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol19.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol18.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol17.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol16.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol15.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol14.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol13.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol12.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol11.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol10.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.btnSymbol1.Clicked += new global::System.EventHandler(this.OnSymbolClicked);
			this.txtSymbols.Changed += new global::System.EventHandler(this.OnTxtSymbolsChanged);
			this.buttonCancel.Pressed += new global::System.EventHandler(this.OnButtonCancelPressed);
			this.buttonOk.Pressed += new global::System.EventHandler(this.OnButtonOkPressed);
		}
	}
}
