
// This file has been generated by the GUI designer. Do not modify.
namespace Zyrenth.OracleHack.GtkUI
{
	public partial class SecretWidget
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Image img1;
		private global::Gtk.Image img11;
		private global::Gtk.Image img2;
		private global::Gtk.Image img3;
		private global::Gtk.Image img4;
		private global::Gtk.Image img12;
		private global::Gtk.Image img13;
		private global::Gtk.Image img14;
		private global::Gtk.Image img5;
		private global::Gtk.Image img6;
		private global::Gtk.Image img16;
		private global::Gtk.Image img7;
		private global::Gtk.Image img17;
		private global::Gtk.Image img8;
		private global::Gtk.Image img15;
		private global::Gtk.Image img18;
		private global::Gtk.Image img19;
		private global::Gtk.Image img20;
		private global::Gtk.Image img10;
		private global::Gtk.Image img9;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zyrenth.OracleHack.GtkUI.SecretWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Zyrenth.OracleHack.GtkUI.SecretWidget";
			// Container child Zyrenth.OracleHack.GtkUI.SecretWidget.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 172;
			this.fixed1.HeightRequest = 52;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img1 = new global::Gtk.Image ();
			this.img1.WidthRequest = 16;
			this.img1.HeightRequest = 20;
			this.img1.Name = "img1";
			this.fixed1.Add (this.img1);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img11 = new global::Gtk.Image ();
			this.img11.WidthRequest = 16;
			this.img11.HeightRequest = 20;
			this.img11.Name = "img11";
			this.fixed1.Add (this.img11);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img11]));
			w2.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img2 = new global::Gtk.Image ();
			this.img2.WidthRequest = 16;
			this.img2.HeightRequest = 20;
			this.img2.Name = "img2";
			this.fixed1.Add (this.img2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img2]));
			w3.X = 16;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img3 = new global::Gtk.Image ();
			this.img3.WidthRequest = 16;
			this.img3.HeightRequest = 20;
			this.img3.Name = "img3";
			this.fixed1.Add (this.img3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img3]));
			w4.X = 32;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img4 = new global::Gtk.Image ();
			this.img4.WidthRequest = 16;
			this.img4.HeightRequest = 20;
			this.img4.Name = "img4";
			this.fixed1.Add (this.img4);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img4]));
			w5.X = 48;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img12 = new global::Gtk.Image ();
			this.img12.WidthRequest = 16;
			this.img12.HeightRequest = 20;
			this.img12.Name = "img12";
			this.fixed1.Add (this.img12);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img12]));
			w6.X = 16;
			w6.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img13 = new global::Gtk.Image ();
			this.img13.WidthRequest = 16;
			this.img13.HeightRequest = 20;
			this.img13.Name = "img13";
			this.fixed1.Add (this.img13);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img13]));
			w7.X = 32;
			w7.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img14 = new global::Gtk.Image ();
			this.img14.WidthRequest = 16;
			this.img14.HeightRequest = 20;
			this.img14.Name = "img14";
			this.fixed1.Add (this.img14);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img14]));
			w8.X = 48;
			w8.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img5 = new global::Gtk.Image ();
			this.img5.WidthRequest = 16;
			this.img5.HeightRequest = 20;
			this.img5.Name = "img5";
			this.fixed1.Add (this.img5);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img5]));
			w9.X = 64;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img6 = new global::Gtk.Image ();
			this.img6.WidthRequest = 16;
			this.img6.HeightRequest = 20;
			this.img6.Name = "img6";
			this.img6.Xpad = 5;
			this.fixed1.Add (this.img6);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img6]));
			w10.X = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img16 = new global::Gtk.Image ();
			this.img16.WidthRequest = 16;
			this.img16.HeightRequest = 20;
			this.img16.Name = "img16";
			this.fixed1.Add (this.img16);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img16]));
			w11.X = 90;
			w11.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img7 = new global::Gtk.Image ();
			this.img7.WidthRequest = 16;
			this.img7.HeightRequest = 20;
			this.img7.Name = "img7";
			this.fixed1.Add (this.img7);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img7]));
			w12.X = 106;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img17 = new global::Gtk.Image ();
			this.img17.WidthRequest = 16;
			this.img17.HeightRequest = 20;
			this.img17.Name = "img17";
			this.fixed1.Add (this.img17);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img17]));
			w13.X = 106;
			w13.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img8 = new global::Gtk.Image ();
			this.img8.WidthRequest = 16;
			this.img8.HeightRequest = 20;
			this.img8.Name = "img8";
			this.fixed1.Add (this.img8);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img8]));
			w14.X = 122;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img15 = new global::Gtk.Image ();
			this.img15.WidthRequest = 16;
			this.img15.HeightRequest = 20;
			this.img15.Name = "img15";
			this.fixed1.Add (this.img15);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img15]));
			w15.X = 64;
			w15.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img18 = new global::Gtk.Image ();
			this.img18.WidthRequest = 16;
			this.img18.HeightRequest = 20;
			this.img18.Name = "img18";
			this.fixed1.Add (this.img18);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img18]));
			w16.X = 122;
			w16.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img19 = new global::Gtk.Image ();
			this.img19.WidthRequest = 16;
			this.img19.HeightRequest = 20;
			this.img19.Name = "img19";
			this.fixed1.Add (this.img19);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img19]));
			w17.X = 138;
			w17.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img20 = new global::Gtk.Image ();
			this.img20.WidthRequest = 16;
			this.img20.HeightRequest = 20;
			this.img20.Name = "img20";
			this.fixed1.Add (this.img20);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img20]));
			w18.X = 154;
			w18.Y = 30;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img10 = new global::Gtk.Image ();
			this.img10.WidthRequest = 16;
			this.img10.HeightRequest = 20;
			this.img10.Name = "img10";
			this.fixed1.Add (this.img10);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img10]));
			w19.X = 154;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.img9 = new global::Gtk.Image ();
			this.img9.WidthRequest = 16;
			this.img9.HeightRequest = 20;
			this.img9.Name = "img9";
			this.fixed1.Add (this.img9);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.img9]));
			w20.X = 138;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
