
// This file has been generated by the GUI designer. Do not modify.
namespace Zyrenth.OracleGtk
{
	public partial class SaveEditor
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label1;
		private global::Gtk.FileChooserButton filechooserbutton1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Frame frmGameType;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.Table table1;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.RadioButton rdoAges;
		private global::Gtk.RadioButton rdoSeasons;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.Table table2;
		private global::Gtk.RadioButton radiobutton3;
		private global::Gtk.RadioButton radiobutton4;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.Table table3;
		private global::Gtk.ComboBox cmbAnimal;
		private global::Gtk.ComboBox cmbBehavior;
		private global::Gtk.Image imgAnimal;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.SpinButton spinID;
		private global::Gtk.Entry txtChild;
		private global::Gtk.Entry txtHero;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button btnEncode;
		private global::Gtk.Button btnRings;
		private global::Gtk.Button btnDecode;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zyrenth.OracleGtk.SaveEditor
			this.Name = "Zyrenth.OracleGtk.SaveEditor";
			this.Title = global::Mono.Unix.Catalog.GetString ("SaveEditor");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Images.Characters.Farore.gif");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(10));
			this.Resizable = false;
			// Container child Zyrenth.OracleGtk.SaveEditor.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("File");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.filechooserbutton1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.filechooserbutton1.WidthRequest = 200;
			this.filechooserbutton1.Name = "filechooserbutton1";
			this.filechooserbutton1.LocalOnly = false;
			this.hbox2.Add (this.filechooserbutton1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.filechooserbutton1]));
			w2.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frmGameType = new global::Gtk.Frame ();
			this.frmGameType.WidthRequest = 0;
			this.frmGameType.HeightRequest = 0;
			this.frmGameType.Name = "frmGameType";
			// Container child frmGameType.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.BorderWidth = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Images.Characters.Nayru.gif");
			this.table1.Add (this.image1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.image1]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Images.Characters.Din.gif");
			this.table1.Add (this.image2);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.image2]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.rdoAges = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Ages"));
			this.rdoAges.CanFocus = true;
			this.rdoAges.Name = "rdoAges";
			this.rdoAges.DrawIndicator = true;
			this.rdoAges.UseUnderline = true;
			this.rdoAges.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table1.Add (this.rdoAges);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.rdoAges]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.rdoSeasons = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Seasons"));
			this.rdoSeasons.CanFocus = true;
			this.rdoSeasons.Name = "rdoSeasons";
			this.rdoSeasons.DrawIndicator = true;
			this.rdoSeasons.UseUnderline = true;
			this.rdoSeasons.Group = this.rdoAges.Group;
			this.table1.Add (this.rdoSeasons);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.rdoSeasons]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table1);
			this.frmGameType.Add (this.GtkAlignment);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("Game");
			this.GtkLabel3.UseMarkup = true;
			this.frmGameType.LabelWidget = this.GtkLabel3;
			this.hbox1.Add (this.frmGameType);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frmGameType]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table2.Name = "table2";
			this.table2.BorderWidth = ((uint)(3));
			// Container child table2.Gtk.Table+TableChild
			this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Linked Quest"));
			this.radiobutton3.CanFocus = true;
			this.radiobutton3.Name = "radiobutton3";
			this.radiobutton3.DrawIndicator = true;
			this.radiobutton3.UseUnderline = true;
			this.radiobutton3.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.table2.Add (this.radiobutton3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.radiobutton3]));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.radiobutton4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Hero's Quest"));
			this.radiobutton4.CanFocus = true;
			this.radiobutton4.Name = "radiobutton4";
			this.radiobutton4.DrawIndicator = true;
			this.radiobutton4.UseUnderline = true;
			this.radiobutton4.Group = this.radiobutton3.Group;
			this.table2.Add (this.radiobutton4);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.radiobutton4]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment1.Add (this.table2);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("Quest Type");
			this.GtkLabel6.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel6;
			this.hbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.cmbAnimal = global::Gtk.ComboBox.NewText ();
			this.cmbAnimal.AppendText (global::Mono.Unix.Catalog.GetString ("None"));
			this.cmbAnimal.AppendText (global::Mono.Unix.Catalog.GetString ("Ricky"));
			this.cmbAnimal.AppendText (global::Mono.Unix.Catalog.GetString ("Dimitri"));
			this.cmbAnimal.AppendText (global::Mono.Unix.Catalog.GetString ("Moosh"));
			this.cmbAnimal.Name = "cmbAnimal";
			this.cmbAnimal.Active = 0;
			this.table3.Add (this.cmbAnimal);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.cmbAnimal]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.cmbBehavior = global::Gtk.ComboBox.NewText ();
			this.cmbBehavior.Name = "cmbBehavior";
			this.table3.Add (this.cmbBehavior);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.cmbBehavior]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(3));
			w18.RightAttach = ((uint)(4));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.imgAnimal = new global::Gtk.Image ();
			this.imgAnimal.Name = "imgAnimal";
			this.table3.Add (this.imgAnimal);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.imgAnimal]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
			this.table3.Add (this.label2);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.label2]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Hero");
			this.table3.Add (this.label3);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.label3]));
			w21.TopAttach = ((uint)(1));
			w21.BottomAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Child");
			this.table3.Add (this.label4);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.label4]));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Behavior");
			this.table3.Add (this.label5);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.label5]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Animal");
			this.table3.Add (this.label6);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinID = new global::Gtk.SpinButton (0, 32767, 1);
			this.spinID.CanFocus = true;
			this.spinID.Name = "spinID";
			this.spinID.Adjustment.PageIncrement = 10;
			this.spinID.ClimbRate = 1;
			this.spinID.Numeric = true;
			this.table3.Add (this.spinID);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinID]));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.txtChild = new global::Gtk.Entry ();
			this.txtChild.WidthRequest = 70;
			this.txtChild.CanFocus = true;
			this.txtChild.Name = "txtChild";
			this.txtChild.IsEditable = true;
			this.txtChild.MaxLength = 5;
			this.txtChild.InvisibleChar = '●';
			this.table3.Add (this.txtChild);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.txtChild]));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.txtHero = new global::Gtk.Entry ();
			this.txtHero.WidthRequest = 70;
			this.txtHero.CanFocus = true;
			this.txtHero.Name = "txtHero";
			this.txtHero.IsEditable = true;
			this.txtHero.MaxLength = 5;
			this.txtHero.InvisibleChar = '●';
			this.table3.Add (this.txtHero);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3 [this.txtHero]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table3]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnEncode = new global::Gtk.Button ();
			this.btnEncode.CanFocus = true;
			this.btnEncode.Name = "btnEncode";
			this.btnEncode.UseUnderline = true;
			this.btnEncode.Label = global::Mono.Unix.Catalog.GetString ("Make Secrets");
			this.hbox3.Add (this.btnEncode);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnEncode]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnRings = new global::Gtk.Button ();
			this.btnRings.CanFocus = true;
			this.btnRings.Name = "btnRings";
			this.btnRings.UseUnderline = true;
			this.btnRings.Label = global::Mono.Unix.Catalog.GetString ("Rings");
			this.hbox3.Add (this.btnRings);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnRings]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnDecode = new global::Gtk.Button ();
			this.btnDecode.CanFocus = true;
			this.btnDecode.Name = "btnDecode";
			this.btnDecode.UseUnderline = true;
			this.btnDecode.Label = global::Mono.Unix.Catalog.GetString ("Decode Secrets");
			this.hbox3.Add (this.btnDecode);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnDecode]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w32.Position = 3;
			w32.Expand = false;
			w32.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 280;
			this.DefaultHeight = 262;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.cmbAnimal.Changed += new global::System.EventHandler (this.OnCmbAnimalChanged);
			this.btnEncode.Clicked += new global::System.EventHandler (this.OnBtnEncodeClicked);
			this.btnRings.Clicked += new global::System.EventHandler (this.OnBtnRingsClicked);
			this.btnDecode.Clicked += new global::System.EventHandler (this.OnBtnDecodeClicked);
		}
	}
}
