
// This file has been generated by the GUI designer. Do not modify.
namespace Zyrenth.OracleHack.GtkUI
{
	public partial class DecoderForm
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Table table3;
		private global::Gtk.Button btnBack;
		private global::Gtk.Button btnReset;
		private global::Zyrenth.OracleHack.GtkUI.SecretWidget secretwidget1;
		private global::Gtk.Table table1;
		private global::Gtk.Button button1;
		private global::Gtk.Image image3;
		private global::Gtk.Button button10;
		private global::Gtk.Image image13;
		private global::Gtk.Button button11;
		private global::Gtk.Image image14;
		private global::Gtk.Button button12;
		private global::Gtk.Image image15;
		private global::Gtk.Button button13;
		private global::Gtk.Image image16;
		private global::Gtk.Button button14;
		private global::Gtk.Image image17;
		private global::Gtk.Button button15;
		private global::Gtk.Image image4;
		private global::Gtk.Button button16;
		private global::Gtk.Image image18;
		private global::Gtk.Button button17;
		private global::Gtk.Image image19;
		private global::Gtk.Button button18;
		private global::Gtk.Image image20;
		private global::Gtk.Button button19;
		private global::Gtk.Image image21;
		private global::Gtk.Button button2;
		private global::Gtk.Image image5;
		private global::Gtk.Button button20;
		private global::Gtk.Image image22;
		private global::Gtk.Button button21;
		private global::Gtk.Image image23;
		private global::Gtk.Button button22;
		private global::Gtk.Image image24;
		private global::Gtk.Button button23;
		private global::Gtk.Image image25;
		private global::Gtk.Button button24;
		private global::Gtk.Image image26;
		private global::Gtk.Button button25;
		private global::Gtk.Image image27;
		private global::Gtk.Button button26;
		private global::Gtk.Image image28;
		private global::Gtk.Button button27;
		private global::Gtk.Image image29;
		private global::Gtk.Button button28;
		private global::Gtk.Image image30;
		private global::Gtk.Button button29;
		private global::Gtk.Image image31;
		private global::Gtk.Button button3;
		private global::Gtk.Image image6;
		private global::Gtk.Button button30;
		private global::Gtk.Image image32;
		private global::Gtk.Button button31;
		private global::Gtk.Image image33;
		private global::Gtk.Button button32;
		private global::Gtk.Image image34;
		private global::Gtk.Button button33;
		private global::Gtk.Image image35;
		private global::Gtk.Button button35;
		private global::Gtk.Image image37;
		private global::Gtk.Button button36;
		private global::Gtk.Image image38;
		private global::Gtk.Button button37;
		private global::Gtk.Image image39;
		private global::Gtk.Button button38;
		private global::Gtk.Image image40;
		private global::Gtk.Button button39;
		private global::Gtk.Image image41;
		private global::Gtk.Button button4;
		private global::Gtk.Image image7;
		private global::Gtk.Button button40;
		private global::Gtk.Image image42;
		private global::Gtk.Button button41;
		private global::Gtk.Image image43;
		private global::Gtk.Button button42;
		private global::Gtk.Image image44;
		private global::Gtk.Button button43;
		private global::Gtk.Image image45;
		private global::Gtk.Button button44;
		private global::Gtk.Image image46;
		private global::Gtk.Button button45;
		private global::Gtk.Image image47;
		private global::Gtk.Button button46;
		private global::Gtk.Image image48;
		private global::Gtk.Button button47;
		private global::Gtk.Image image49;
		private global::Gtk.Button button48;
		private global::Gtk.Image image50;
		private global::Gtk.Button button49;
		private global::Gtk.Image image51;
		private global::Gtk.Button button5;
		private global::Gtk.Image image8;
		private global::Gtk.Button button50;
		private global::Gtk.Image image52;
		private global::Gtk.Button button51;
		private global::Gtk.Image image53;
		private global::Gtk.Button button52;
		private global::Gtk.Image image54;
		private global::Gtk.Button button53;
		private global::Gtk.Image image55;
		private global::Gtk.Button button54;
		private global::Gtk.Image image56;
		private global::Gtk.Button button55;
		private global::Gtk.Image image57;
		private global::Gtk.Button button56;
		private global::Gtk.Image image58;
		private global::Gtk.Button button57;
		private global::Gtk.Image image59;
		private global::Gtk.Button button58;
		private global::Gtk.Image image60;
		private global::Gtk.Button button59;
		private global::Gtk.Image image61;
		private global::Gtk.Button button6;
		private global::Gtk.Image image9;
		private global::Gtk.Button button60;
		private global::Gtk.Image image62;
		private global::Gtk.Button button61;
		private global::Gtk.Image image63;
		private global::Gtk.Button button62;
		private global::Gtk.Image image64;
		private global::Gtk.Button button63;
		private global::Gtk.Image image65;
		private global::Gtk.Button button64;
		private global::Gtk.Image image66;
		private global::Gtk.Button button65;
		private global::Gtk.Image image67;
		private global::Gtk.Button button7;
		private global::Gtk.Image image10;
		private global::Gtk.Button button8;
		private global::Gtk.Image image11;
		private global::Gtk.Button button9;
		private global::Gtk.Image image12;
		private global::Gtk.HBox hbox2;
		private global::Gtk.CheckButton chkAppendRings;
		private global::Gtk.Button btnDone;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zyrenth.OracleHack.GtkUI.DecoderForm
			this.Name = "Zyrenth.OracleHack.GtkUI.DecoderForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("DecoderForm");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Characters.Farore.gif");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Zyrenth.OracleHack.GtkUI.DecoderForm.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			// Container child table3.Gtk.Table+TableChild
			this.btnBack = new global::Gtk.Button ();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString ("Back");
			this.table3.Add (this.btnBack);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnBack]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XPadding = ((uint)(5));
			w1.YPadding = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.btnReset = new global::Gtk.Button ();
			this.btnReset.CanFocus = true;
			this.btnReset.Name = "btnReset";
			this.btnReset.UseUnderline = true;
			this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.table3.Add (this.btnReset);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnReset]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XPadding = ((uint)(5));
			w2.YPadding = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.secretwidget1 = new global::Zyrenth.OracleHack.GtkUI.SecretWidget ();
			this.secretwidget1.Events = ((global::Gdk.EventMask)(256));
			this.secretwidget1.Name = "secretwidget1";
			this.table3.Add (this.secretwidget1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.secretwidget1]));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(13)), false);
			this.table1.Name = "table1";
			// Container child table1.Gtk.Table+TableChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			// Container child button1.Gtk.Container+ContainerChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.00.png");
			this.button1.Add (this.image3);
			this.button1.Label = null;
			this.table1.Add (this.button1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.button1]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			// Container child button10.Gtk.Container+ContainerChild
			this.image13 = new global::Gtk.Image ();
			this.image13.Name = "image13";
			this.image13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.09.png");
			this.button10.Add (this.image13);
			this.button10.Label = null;
			this.table1.Add (this.button10);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.button10]));
			w8.LeftAttach = ((uint)(9));
			w8.RightAttach = ((uint)(10));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button11 = new global::Gtk.Button ();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			// Container child button11.Gtk.Container+ContainerChild
			this.image14 = new global::Gtk.Image ();
			this.image14.Name = "image14";
			this.image14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.10.png");
			this.button11.Add (this.image14);
			this.button11.Label = null;
			this.table1.Add (this.button11);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.button11]));
			w10.LeftAttach = ((uint)(10));
			w10.RightAttach = ((uint)(11));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button12 = new global::Gtk.Button ();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			// Container child button12.Gtk.Container+ContainerChild
			this.image15 = new global::Gtk.Image ();
			this.image15.Name = "image15";
			this.image15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.11.png");
			this.button12.Add (this.image15);
			this.button12.Label = null;
			this.table1.Add (this.button12);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.button12]));
			w12.LeftAttach = ((uint)(11));
			w12.RightAttach = ((uint)(12));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button13 = new global::Gtk.Button ();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			// Container child button13.Gtk.Container+ContainerChild
			this.image16 = new global::Gtk.Image ();
			this.image16.Name = "image16";
			this.image16.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.12.png");
			this.button13.Add (this.image16);
			this.button13.Label = null;
			this.table1.Add (this.button13);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.button13]));
			w14.LeftAttach = ((uint)(12));
			w14.RightAttach = ((uint)(13));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button14 = new global::Gtk.Button ();
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			// Container child button14.Gtk.Container+ContainerChild
			this.image17 = new global::Gtk.Image ();
			this.image17.Name = "image17";
			this.image17.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.13.png");
			this.button14.Add (this.image17);
			this.button14.Label = null;
			this.table1.Add (this.button14);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.button14]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button15 = new global::Gtk.Button ();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			// Container child button15.Gtk.Container+ContainerChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.14.png");
			this.button15.Add (this.image4);
			this.button15.Label = null;
			this.table1.Add (this.button15);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.button15]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button16 = new global::Gtk.Button ();
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			// Container child button16.Gtk.Container+ContainerChild
			this.image18 = new global::Gtk.Image ();
			this.image18.Name = "image18";
			this.image18.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.15.png");
			this.button16.Add (this.image18);
			this.button16.Label = null;
			this.table1.Add (this.button16);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.button16]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button17 = new global::Gtk.Button ();
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			// Container child button17.Gtk.Container+ContainerChild
			this.image19 = new global::Gtk.Image ();
			this.image19.Name = "image19";
			this.image19.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.16.png");
			this.button17.Add (this.image19);
			this.button17.Label = null;
			this.table1.Add (this.button17);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.button17]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(3));
			w22.RightAttach = ((uint)(4));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button18 = new global::Gtk.Button ();
			this.button18.CanFocus = true;
			this.button18.Name = "button18";
			// Container child button18.Gtk.Container+ContainerChild
			this.image20 = new global::Gtk.Image ();
			this.image20.Name = "image20";
			this.image20.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.17.png");
			this.button18.Add (this.image20);
			this.button18.Label = null;
			this.table1.Add (this.button18);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.button18]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.LeftAttach = ((uint)(4));
			w24.RightAttach = ((uint)(5));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button19 = new global::Gtk.Button ();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			// Container child button19.Gtk.Container+ContainerChild
			this.image21 = new global::Gtk.Image ();
			this.image21.Name = "image21";
			this.image21.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.18.png");
			this.button19.Add (this.image21);
			this.button19.Label = null;
			this.table1.Add (this.button19);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.button19]));
			w26.TopAttach = ((uint)(1));
			w26.BottomAttach = ((uint)(2));
			w26.LeftAttach = ((uint)(5));
			w26.RightAttach = ((uint)(6));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			// Container child button2.Gtk.Container+ContainerChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.01.png");
			this.button2.Add (this.image5);
			this.button2.Label = null;
			this.table1.Add (this.button2);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.button2]));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button20 = new global::Gtk.Button ();
			this.button20.CanFocus = true;
			this.button20.Name = "button20";
			// Container child button20.Gtk.Container+ContainerChild
			this.image22 = new global::Gtk.Image ();
			this.image22.Name = "image22";
			this.image22.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.20.png");
			this.button20.Add (this.image22);
			this.button20.Label = null;
			this.table1.Add (this.button20);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.button20]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.LeftAttach = ((uint)(7));
			w30.RightAttach = ((uint)(8));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button21 = new global::Gtk.Button ();
			this.button21.CanFocus = true;
			this.button21.Name = "button21";
			// Container child button21.Gtk.Container+ContainerChild
			this.image23 = new global::Gtk.Image ();
			this.image23.Name = "image23";
			this.image23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.19.png");
			this.button21.Add (this.image23);
			this.button21.Label = null;
			this.table1.Add (this.button21);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.button21]));
			w32.TopAttach = ((uint)(1));
			w32.BottomAttach = ((uint)(2));
			w32.LeftAttach = ((uint)(6));
			w32.RightAttach = ((uint)(7));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button22 = new global::Gtk.Button ();
			this.button22.CanFocus = true;
			this.button22.Name = "button22";
			// Container child button22.Gtk.Container+ContainerChild
			this.image24 = new global::Gtk.Image ();
			this.image24.Name = "image24";
			this.image24.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.21.png");
			this.button22.Add (this.image24);
			this.button22.Label = null;
			this.table1.Add (this.button22);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.button22]));
			w34.TopAttach = ((uint)(1));
			w34.BottomAttach = ((uint)(2));
			w34.LeftAttach = ((uint)(8));
			w34.RightAttach = ((uint)(9));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button23 = new global::Gtk.Button ();
			this.button23.CanFocus = true;
			this.button23.Name = "button23";
			// Container child button23.Gtk.Container+ContainerChild
			this.image25 = new global::Gtk.Image ();
			this.image25.Name = "image25";
			this.image25.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.22.png");
			this.button23.Add (this.image25);
			this.button23.Label = null;
			this.table1.Add (this.button23);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.button23]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.LeftAttach = ((uint)(9));
			w36.RightAttach = ((uint)(10));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button24 = new global::Gtk.Button ();
			this.button24.CanFocus = true;
			this.button24.Name = "button24";
			// Container child button24.Gtk.Container+ContainerChild
			this.image26 = new global::Gtk.Image ();
			this.image26.Name = "image26";
			this.image26.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.23.png");
			this.button24.Add (this.image26);
			this.button24.Label = null;
			this.table1.Add (this.button24);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1 [this.button24]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.LeftAttach = ((uint)(10));
			w38.RightAttach = ((uint)(11));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button25 = new global::Gtk.Button ();
			this.button25.CanFocus = true;
			this.button25.Name = "button25";
			// Container child button25.Gtk.Container+ContainerChild
			this.image27 = new global::Gtk.Image ();
			this.image27.Name = "image27";
			this.image27.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.24.png");
			this.button25.Add (this.image27);
			this.button25.Label = null;
			this.table1.Add (this.button25);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1 [this.button25]));
			w40.TopAttach = ((uint)(1));
			w40.BottomAttach = ((uint)(2));
			w40.LeftAttach = ((uint)(11));
			w40.RightAttach = ((uint)(12));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button26 = new global::Gtk.Button ();
			this.button26.CanFocus = true;
			this.button26.Name = "button26";
			// Container child button26.Gtk.Container+ContainerChild
			this.image28 = new global::Gtk.Image ();
			this.image28.Name = "image28";
			this.image28.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.25.png");
			this.button26.Add (this.image28);
			this.button26.Label = null;
			this.table1.Add (this.button26);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1 [this.button26]));
			w42.TopAttach = ((uint)(1));
			w42.BottomAttach = ((uint)(2));
			w42.LeftAttach = ((uint)(12));
			w42.RightAttach = ((uint)(13));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button27 = new global::Gtk.Button ();
			this.button27.CanFocus = true;
			this.button27.Name = "button27";
			// Container child button27.Gtk.Container+ContainerChild
			this.image29 = new global::Gtk.Image ();
			this.image29.Name = "image29";
			this.image29.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.26.png");
			this.button27.Add (this.image29);
			this.button27.Label = null;
			this.table1.Add (this.button27);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1 [this.button27]));
			w44.TopAttach = ((uint)(2));
			w44.BottomAttach = ((uint)(3));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button28 = new global::Gtk.Button ();
			this.button28.CanFocus = true;
			this.button28.Name = "button28";
			// Container child button28.Gtk.Container+ContainerChild
			this.image30 = new global::Gtk.Image ();
			this.image30.Name = "image30";
			this.image30.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.27.png");
			this.button28.Add (this.image30);
			this.button28.Label = null;
			this.table1.Add (this.button28);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1 [this.button28]));
			w46.TopAttach = ((uint)(2));
			w46.BottomAttach = ((uint)(3));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button29 = new global::Gtk.Button ();
			this.button29.CanFocus = true;
			this.button29.Name = "button29";
			// Container child button29.Gtk.Container+ContainerChild
			this.image31 = new global::Gtk.Image ();
			this.image31.Name = "image31";
			this.image31.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.28.png");
			this.button29.Add (this.image31);
			this.button29.Label = null;
			this.table1.Add (this.button29);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1 [this.button29]));
			w48.TopAttach = ((uint)(2));
			w48.BottomAttach = ((uint)(3));
			w48.LeftAttach = ((uint)(2));
			w48.RightAttach = ((uint)(3));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			// Container child button3.Gtk.Container+ContainerChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.02.png");
			this.button3.Add (this.image6);
			this.button3.Label = null;
			this.table1.Add (this.button3);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1 [this.button3]));
			w50.LeftAttach = ((uint)(2));
			w50.RightAttach = ((uint)(3));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button30 = new global::Gtk.Button ();
			this.button30.CanFocus = true;
			this.button30.Name = "button30";
			// Container child button30.Gtk.Container+ContainerChild
			this.image32 = new global::Gtk.Image ();
			this.image32.Name = "image32";
			this.image32.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.29.png");
			this.button30.Add (this.image32);
			this.button30.Label = null;
			this.table1.Add (this.button30);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1 [this.button30]));
			w52.TopAttach = ((uint)(2));
			w52.BottomAttach = ((uint)(3));
			w52.LeftAttach = ((uint)(3));
			w52.RightAttach = ((uint)(4));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button31 = new global::Gtk.Button ();
			this.button31.CanFocus = true;
			this.button31.Name = "button31";
			// Container child button31.Gtk.Container+ContainerChild
			this.image33 = new global::Gtk.Image ();
			this.image33.Name = "image33";
			this.image33.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.30.png");
			this.button31.Add (this.image33);
			this.button31.Label = null;
			this.table1.Add (this.button31);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table1 [this.button31]));
			w54.TopAttach = ((uint)(2));
			w54.BottomAttach = ((uint)(3));
			w54.LeftAttach = ((uint)(4));
			w54.RightAttach = ((uint)(5));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button32 = new global::Gtk.Button ();
			this.button32.CanFocus = true;
			this.button32.Name = "button32";
			// Container child button32.Gtk.Container+ContainerChild
			this.image34 = new global::Gtk.Image ();
			this.image34.Name = "image34";
			this.image34.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.31.png");
			this.button32.Add (this.image34);
			this.button32.Label = null;
			this.table1.Add (this.button32);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table1 [this.button32]));
			w56.TopAttach = ((uint)(2));
			w56.BottomAttach = ((uint)(3));
			w56.LeftAttach = ((uint)(5));
			w56.RightAttach = ((uint)(6));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button33 = new global::Gtk.Button ();
			this.button33.CanFocus = true;
			this.button33.Name = "button33";
			// Container child button33.Gtk.Container+ContainerChild
			this.image35 = new global::Gtk.Image ();
			this.image35.Name = "image35";
			this.image35.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.32.png");
			this.button33.Add (this.image35);
			this.button33.Label = null;
			this.table1.Add (this.button33);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table1 [this.button33]));
			w58.TopAttach = ((uint)(2));
			w58.BottomAttach = ((uint)(3));
			w58.LeftAttach = ((uint)(7));
			w58.RightAttach = ((uint)(8));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button35 = new global::Gtk.Button ();
			this.button35.CanFocus = true;
			this.button35.Name = "button35";
			// Container child button35.Gtk.Container+ContainerChild
			this.image37 = new global::Gtk.Image ();
			this.image37.Name = "image37";
			this.image37.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.33.png");
			this.button35.Add (this.image37);
			this.button35.Label = null;
			this.table1.Add (this.button35);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table1 [this.button35]));
			w60.TopAttach = ((uint)(2));
			w60.BottomAttach = ((uint)(3));
			w60.LeftAttach = ((uint)(8));
			w60.RightAttach = ((uint)(9));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button36 = new global::Gtk.Button ();
			this.button36.CanFocus = true;
			this.button36.Name = "button36";
			// Container child button36.Gtk.Container+ContainerChild
			this.image38 = new global::Gtk.Image ();
			this.image38.Name = "image38";
			this.image38.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.34.png");
			this.button36.Add (this.image38);
			this.button36.Label = null;
			this.table1.Add (this.button36);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table1 [this.button36]));
			w62.TopAttach = ((uint)(2));
			w62.BottomAttach = ((uint)(3));
			w62.LeftAttach = ((uint)(9));
			w62.RightAttach = ((uint)(10));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button37 = new global::Gtk.Button ();
			this.button37.CanFocus = true;
			this.button37.Name = "button37";
			// Container child button37.Gtk.Container+ContainerChild
			this.image39 = new global::Gtk.Image ();
			this.image39.Name = "image39";
			this.image39.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.35.png");
			this.button37.Add (this.image39);
			this.button37.Label = null;
			this.table1.Add (this.button37);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1 [this.button37]));
			w64.TopAttach = ((uint)(2));
			w64.BottomAttach = ((uint)(3));
			w64.LeftAttach = ((uint)(10));
			w64.RightAttach = ((uint)(11));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button38 = new global::Gtk.Button ();
			this.button38.CanFocus = true;
			this.button38.Name = "button38";
			// Container child button38.Gtk.Container+ContainerChild
			this.image40 = new global::Gtk.Image ();
			this.image40.Name = "image40";
			this.image40.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.36.png");
			this.button38.Add (this.image40);
			this.button38.Label = null;
			this.table1.Add (this.button38);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table1 [this.button38]));
			w66.TopAttach = ((uint)(2));
			w66.BottomAttach = ((uint)(3));
			w66.LeftAttach = ((uint)(11));
			w66.RightAttach = ((uint)(12));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button39 = new global::Gtk.Button ();
			this.button39.CanFocus = true;
			this.button39.Name = "button39";
			// Container child button39.Gtk.Container+ContainerChild
			this.image41 = new global::Gtk.Image ();
			this.image41.Name = "image41";
			this.image41.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.37.png");
			this.button39.Add (this.image41);
			this.button39.Label = null;
			this.table1.Add (this.button39);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table1 [this.button39]));
			w68.TopAttach = ((uint)(2));
			w68.BottomAttach = ((uint)(3));
			w68.LeftAttach = ((uint)(12));
			w68.RightAttach = ((uint)(13));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			// Container child button4.Gtk.Container+ContainerChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.03.png");
			this.button4.Add (this.image7);
			this.button4.Label = null;
			this.table1.Add (this.button4);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table1 [this.button4]));
			w70.LeftAttach = ((uint)(3));
			w70.RightAttach = ((uint)(4));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button40 = new global::Gtk.Button ();
			this.button40.CanFocus = true;
			this.button40.Name = "button40";
			// Container child button40.Gtk.Container+ContainerChild
			this.image42 = new global::Gtk.Image ();
			this.image42.Name = "image42";
			this.image42.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.38.png");
			this.button40.Add (this.image42);
			this.button40.Label = null;
			this.table1.Add (this.button40);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table1 [this.button40]));
			w72.TopAttach = ((uint)(3));
			w72.BottomAttach = ((uint)(4));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button41 = new global::Gtk.Button ();
			this.button41.CanFocus = true;
			this.button41.Name = "button41";
			// Container child button41.Gtk.Container+ContainerChild
			this.image43 = new global::Gtk.Image ();
			this.image43.Name = "image43";
			this.image43.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.39.png");
			this.button41.Add (this.image43);
			this.button41.Label = null;
			this.table1.Add (this.button41);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table1 [this.button41]));
			w74.TopAttach = ((uint)(3));
			w74.BottomAttach = ((uint)(4));
			w74.LeftAttach = ((uint)(1));
			w74.RightAttach = ((uint)(2));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button42 = new global::Gtk.Button ();
			this.button42.CanFocus = true;
			this.button42.Name = "button42";
			// Container child button42.Gtk.Container+ContainerChild
			this.image44 = new global::Gtk.Image ();
			this.image44.Name = "image44";
			this.image44.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.40.png");
			this.button42.Add (this.image44);
			this.button42.Label = null;
			this.table1.Add (this.button42);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table1 [this.button42]));
			w76.TopAttach = ((uint)(3));
			w76.BottomAttach = ((uint)(4));
			w76.LeftAttach = ((uint)(2));
			w76.RightAttach = ((uint)(3));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button43 = new global::Gtk.Button ();
			this.button43.CanFocus = true;
			this.button43.Name = "button43";
			// Container child button43.Gtk.Container+ContainerChild
			this.image45 = new global::Gtk.Image ();
			this.image45.Name = "image45";
			this.image45.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.41.png");
			this.button43.Add (this.image45);
			this.button43.Label = null;
			this.table1.Add (this.button43);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table1 [this.button43]));
			w78.TopAttach = ((uint)(3));
			w78.BottomAttach = ((uint)(4));
			w78.LeftAttach = ((uint)(3));
			w78.RightAttach = ((uint)(4));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button44 = new global::Gtk.Button ();
			this.button44.CanFocus = true;
			this.button44.Name = "button44";
			// Container child button44.Gtk.Container+ContainerChild
			this.image46 = new global::Gtk.Image ();
			this.image46.Name = "image46";
			this.image46.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.42.png");
			this.button44.Add (this.image46);
			this.button44.Label = null;
			this.table1.Add (this.button44);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table1 [this.button44]));
			w80.TopAttach = ((uint)(3));
			w80.BottomAttach = ((uint)(4));
			w80.LeftAttach = ((uint)(4));
			w80.RightAttach = ((uint)(5));
			w80.XOptions = ((global::Gtk.AttachOptions)(4));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button45 = new global::Gtk.Button ();
			this.button45.CanFocus = true;
			this.button45.Name = "button45";
			// Container child button45.Gtk.Container+ContainerChild
			this.image47 = new global::Gtk.Image ();
			this.image47.Name = "image47";
			this.image47.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.43.png");
			this.button45.Add (this.image47);
			this.button45.Label = null;
			this.table1.Add (this.button45);
			global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table1 [this.button45]));
			w82.TopAttach = ((uint)(3));
			w82.BottomAttach = ((uint)(4));
			w82.LeftAttach = ((uint)(5));
			w82.RightAttach = ((uint)(6));
			w82.XOptions = ((global::Gtk.AttachOptions)(4));
			w82.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button46 = new global::Gtk.Button ();
			this.button46.CanFocus = true;
			this.button46.Name = "button46";
			// Container child button46.Gtk.Container+ContainerChild
			this.image48 = new global::Gtk.Image ();
			this.image48.Name = "image48";
			this.image48.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.44.png");
			this.button46.Add (this.image48);
			this.button46.Label = null;
			this.table1.Add (this.button46);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table1 [this.button46]));
			w84.TopAttach = ((uint)(3));
			w84.BottomAttach = ((uint)(4));
			w84.LeftAttach = ((uint)(6));
			w84.RightAttach = ((uint)(7));
			w84.XOptions = ((global::Gtk.AttachOptions)(4));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button47 = new global::Gtk.Button ();
			this.button47.CanFocus = true;
			this.button47.Name = "button47";
			// Container child button47.Gtk.Container+ContainerChild
			this.image49 = new global::Gtk.Image ();
			this.image49.Name = "image49";
			this.image49.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.45.png");
			this.button47.Add (this.image49);
			this.button47.Label = null;
			this.table1.Add (this.button47);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table1 [this.button47]));
			w86.TopAttach = ((uint)(3));
			w86.BottomAttach = ((uint)(4));
			w86.LeftAttach = ((uint)(7));
			w86.RightAttach = ((uint)(8));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button48 = new global::Gtk.Button ();
			this.button48.CanFocus = true;
			this.button48.Name = "button48";
			// Container child button48.Gtk.Container+ContainerChild
			this.image50 = new global::Gtk.Image ();
			this.image50.Name = "image50";
			this.image50.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.46.png");
			this.button48.Add (this.image50);
			this.button48.Label = null;
			this.table1.Add (this.button48);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table1 [this.button48]));
			w88.TopAttach = ((uint)(3));
			w88.BottomAttach = ((uint)(4));
			w88.LeftAttach = ((uint)(8));
			w88.RightAttach = ((uint)(9));
			w88.XOptions = ((global::Gtk.AttachOptions)(4));
			w88.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button49 = new global::Gtk.Button ();
			this.button49.CanFocus = true;
			this.button49.Name = "button49";
			// Container child button49.Gtk.Container+ContainerChild
			this.image51 = new global::Gtk.Image ();
			this.image51.Name = "image51";
			this.image51.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.47.png");
			this.button49.Add (this.image51);
			this.button49.Label = null;
			this.table1.Add (this.button49);
			global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.table1 [this.button49]));
			w90.TopAttach = ((uint)(3));
			w90.BottomAttach = ((uint)(4));
			w90.LeftAttach = ((uint)(9));
			w90.RightAttach = ((uint)(10));
			w90.XOptions = ((global::Gtk.AttachOptions)(4));
			w90.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			// Container child button5.Gtk.Container+ContainerChild
			this.image8 = new global::Gtk.Image ();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.04.png");
			this.button5.Add (this.image8);
			this.button5.Label = null;
			this.table1.Add (this.button5);
			global::Gtk.Table.TableChild w92 = ((global::Gtk.Table.TableChild)(this.table1 [this.button5]));
			w92.LeftAttach = ((uint)(4));
			w92.RightAttach = ((uint)(5));
			w92.XOptions = ((global::Gtk.AttachOptions)(4));
			w92.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button50 = new global::Gtk.Button ();
			this.button50.CanFocus = true;
			this.button50.Name = "button50";
			// Container child button50.Gtk.Container+ContainerChild
			this.image52 = new global::Gtk.Image ();
			this.image52.Name = "image52";
			this.image52.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.48.png");
			this.button50.Add (this.image52);
			this.button50.Label = null;
			this.table1.Add (this.button50);
			global::Gtk.Table.TableChild w94 = ((global::Gtk.Table.TableChild)(this.table1 [this.button50]));
			w94.TopAttach = ((uint)(3));
			w94.BottomAttach = ((uint)(4));
			w94.LeftAttach = ((uint)(10));
			w94.RightAttach = ((uint)(11));
			w94.XOptions = ((global::Gtk.AttachOptions)(4));
			w94.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button51 = new global::Gtk.Button ();
			this.button51.CanFocus = true;
			this.button51.Name = "button51";
			// Container child button51.Gtk.Container+ContainerChild
			this.image53 = new global::Gtk.Image ();
			this.image53.Name = "image53";
			this.image53.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.49.png");
			this.button51.Add (this.image53);
			this.button51.Label = null;
			this.table1.Add (this.button51);
			global::Gtk.Table.TableChild w96 = ((global::Gtk.Table.TableChild)(this.table1 [this.button51]));
			w96.TopAttach = ((uint)(3));
			w96.BottomAttach = ((uint)(4));
			w96.LeftAttach = ((uint)(11));
			w96.RightAttach = ((uint)(12));
			w96.XOptions = ((global::Gtk.AttachOptions)(4));
			w96.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button52 = new global::Gtk.Button ();
			this.button52.CanFocus = true;
			this.button52.Name = "button52";
			// Container child button52.Gtk.Container+ContainerChild
			this.image54 = new global::Gtk.Image ();
			this.image54.Name = "image54";
			this.image54.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.50.png");
			this.button52.Add (this.image54);
			this.button52.Label = null;
			this.table1.Add (this.button52);
			global::Gtk.Table.TableChild w98 = ((global::Gtk.Table.TableChild)(this.table1 [this.button52]));
			w98.TopAttach = ((uint)(3));
			w98.BottomAttach = ((uint)(4));
			w98.LeftAttach = ((uint)(12));
			w98.RightAttach = ((uint)(13));
			w98.XOptions = ((global::Gtk.AttachOptions)(4));
			w98.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button53 = new global::Gtk.Button ();
			this.button53.CanFocus = true;
			this.button53.Name = "button53";
			// Container child button53.Gtk.Container+ContainerChild
			this.image55 = new global::Gtk.Image ();
			this.image55.Name = "image55";
			this.image55.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.51.png");
			this.button53.Add (this.image55);
			this.button53.Label = null;
			this.table1.Add (this.button53);
			global::Gtk.Table.TableChild w100 = ((global::Gtk.Table.TableChild)(this.table1 [this.button53]));
			w100.TopAttach = ((uint)(4));
			w100.BottomAttach = ((uint)(5));
			w100.XOptions = ((global::Gtk.AttachOptions)(4));
			w100.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button54 = new global::Gtk.Button ();
			this.button54.CanFocus = true;
			this.button54.Name = "button54";
			// Container child button54.Gtk.Container+ContainerChild
			this.image56 = new global::Gtk.Image ();
			this.image56.Name = "image56";
			this.image56.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.52.png");
			this.button54.Add (this.image56);
			this.button54.Label = null;
			this.table1.Add (this.button54);
			global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.table1 [this.button54]));
			w102.TopAttach = ((uint)(4));
			w102.BottomAttach = ((uint)(5));
			w102.LeftAttach = ((uint)(1));
			w102.RightAttach = ((uint)(2));
			w102.XOptions = ((global::Gtk.AttachOptions)(4));
			w102.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button55 = new global::Gtk.Button ();
			this.button55.CanFocus = true;
			this.button55.Name = "button55";
			// Container child button55.Gtk.Container+ContainerChild
			this.image57 = new global::Gtk.Image ();
			this.image57.Name = "image57";
			this.image57.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.53.png");
			this.button55.Add (this.image57);
			this.button55.Label = null;
			this.table1.Add (this.button55);
			global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.table1 [this.button55]));
			w104.TopAttach = ((uint)(4));
			w104.BottomAttach = ((uint)(5));
			w104.LeftAttach = ((uint)(2));
			w104.RightAttach = ((uint)(3));
			w104.XOptions = ((global::Gtk.AttachOptions)(4));
			w104.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button56 = new global::Gtk.Button ();
			this.button56.CanFocus = true;
			this.button56.Name = "button56";
			// Container child button56.Gtk.Container+ContainerChild
			this.image58 = new global::Gtk.Image ();
			this.image58.Name = "image58";
			this.image58.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.54.png");
			this.button56.Add (this.image58);
			this.button56.Label = null;
			this.table1.Add (this.button56);
			global::Gtk.Table.TableChild w106 = ((global::Gtk.Table.TableChild)(this.table1 [this.button56]));
			w106.TopAttach = ((uint)(4));
			w106.BottomAttach = ((uint)(5));
			w106.LeftAttach = ((uint)(3));
			w106.RightAttach = ((uint)(4));
			w106.XOptions = ((global::Gtk.AttachOptions)(4));
			w106.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button57 = new global::Gtk.Button ();
			this.button57.CanFocus = true;
			this.button57.Name = "button57";
			// Container child button57.Gtk.Container+ContainerChild
			this.image59 = new global::Gtk.Image ();
			this.image59.Name = "image59";
			this.image59.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.55.png");
			this.button57.Add (this.image59);
			this.button57.Label = null;
			this.table1.Add (this.button57);
			global::Gtk.Table.TableChild w108 = ((global::Gtk.Table.TableChild)(this.table1 [this.button57]));
			w108.TopAttach = ((uint)(4));
			w108.BottomAttach = ((uint)(5));
			w108.LeftAttach = ((uint)(4));
			w108.RightAttach = ((uint)(5));
			w108.XOptions = ((global::Gtk.AttachOptions)(4));
			w108.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button58 = new global::Gtk.Button ();
			this.button58.CanFocus = true;
			this.button58.Name = "button58";
			// Container child button58.Gtk.Container+ContainerChild
			this.image60 = new global::Gtk.Image ();
			this.image60.Name = "image60";
			this.image60.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.56.png");
			this.button58.Add (this.image60);
			this.button58.Label = null;
			this.table1.Add (this.button58);
			global::Gtk.Table.TableChild w110 = ((global::Gtk.Table.TableChild)(this.table1 [this.button58]));
			w110.TopAttach = ((uint)(4));
			w110.BottomAttach = ((uint)(5));
			w110.LeftAttach = ((uint)(5));
			w110.RightAttach = ((uint)(6));
			w110.XOptions = ((global::Gtk.AttachOptions)(4));
			w110.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button59 = new global::Gtk.Button ();
			this.button59.CanFocus = true;
			this.button59.Name = "button59";
			// Container child button59.Gtk.Container+ContainerChild
			this.image61 = new global::Gtk.Image ();
			this.image61.Name = "image61";
			this.image61.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.57.png");
			this.button59.Add (this.image61);
			this.button59.Label = null;
			this.table1.Add (this.button59);
			global::Gtk.Table.TableChild w112 = ((global::Gtk.Table.TableChild)(this.table1 [this.button59]));
			w112.TopAttach = ((uint)(4));
			w112.BottomAttach = ((uint)(5));
			w112.LeftAttach = ((uint)(6));
			w112.RightAttach = ((uint)(7));
			w112.XOptions = ((global::Gtk.AttachOptions)(4));
			w112.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			// Container child button6.Gtk.Container+ContainerChild
			this.image9 = new global::Gtk.Image ();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.05.png");
			this.button6.Add (this.image9);
			this.button6.Label = null;
			this.table1.Add (this.button6);
			global::Gtk.Table.TableChild w114 = ((global::Gtk.Table.TableChild)(this.table1 [this.button6]));
			w114.LeftAttach = ((uint)(5));
			w114.RightAttach = ((uint)(6));
			w114.XOptions = ((global::Gtk.AttachOptions)(4));
			w114.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button60 = new global::Gtk.Button ();
			this.button60.CanFocus = true;
			this.button60.Name = "button60";
			// Container child button60.Gtk.Container+ContainerChild
			this.image62 = new global::Gtk.Image ();
			this.image62.Name = "image62";
			this.image62.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.58.png");
			this.button60.Add (this.image62);
			this.button60.Label = null;
			this.table1.Add (this.button60);
			global::Gtk.Table.TableChild w116 = ((global::Gtk.Table.TableChild)(this.table1 [this.button60]));
			w116.TopAttach = ((uint)(4));
			w116.BottomAttach = ((uint)(5));
			w116.LeftAttach = ((uint)(7));
			w116.RightAttach = ((uint)(8));
			w116.XOptions = ((global::Gtk.AttachOptions)(4));
			w116.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button61 = new global::Gtk.Button ();
			this.button61.CanFocus = true;
			this.button61.Name = "button61";
			// Container child button61.Gtk.Container+ContainerChild
			this.image63 = new global::Gtk.Image ();
			this.image63.Name = "image63";
			this.image63.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.59.png");
			this.button61.Add (this.image63);
			this.button61.Label = null;
			this.table1.Add (this.button61);
			global::Gtk.Table.TableChild w118 = ((global::Gtk.Table.TableChild)(this.table1 [this.button61]));
			w118.TopAttach = ((uint)(4));
			w118.BottomAttach = ((uint)(5));
			w118.LeftAttach = ((uint)(8));
			w118.RightAttach = ((uint)(9));
			w118.XOptions = ((global::Gtk.AttachOptions)(4));
			w118.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button62 = new global::Gtk.Button ();
			this.button62.CanFocus = true;
			this.button62.Name = "button62";
			// Container child button62.Gtk.Container+ContainerChild
			this.image64 = new global::Gtk.Image ();
			this.image64.Name = "image64";
			this.image64.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.60.png");
			this.button62.Add (this.image64);
			this.button62.Label = null;
			this.table1.Add (this.button62);
			global::Gtk.Table.TableChild w120 = ((global::Gtk.Table.TableChild)(this.table1 [this.button62]));
			w120.TopAttach = ((uint)(4));
			w120.BottomAttach = ((uint)(5));
			w120.LeftAttach = ((uint)(9));
			w120.RightAttach = ((uint)(10));
			w120.XOptions = ((global::Gtk.AttachOptions)(4));
			w120.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button63 = new global::Gtk.Button ();
			this.button63.CanFocus = true;
			this.button63.Name = "button63";
			// Container child button63.Gtk.Container+ContainerChild
			this.image65 = new global::Gtk.Image ();
			this.image65.Name = "image65";
			this.image65.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.61.png");
			this.button63.Add (this.image65);
			this.button63.Label = null;
			this.table1.Add (this.button63);
			global::Gtk.Table.TableChild w122 = ((global::Gtk.Table.TableChild)(this.table1 [this.button63]));
			w122.TopAttach = ((uint)(4));
			w122.BottomAttach = ((uint)(5));
			w122.LeftAttach = ((uint)(10));
			w122.RightAttach = ((uint)(11));
			w122.XOptions = ((global::Gtk.AttachOptions)(4));
			w122.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button64 = new global::Gtk.Button ();
			this.button64.CanFocus = true;
			this.button64.Name = "button64";
			// Container child button64.Gtk.Container+ContainerChild
			this.image66 = new global::Gtk.Image ();
			this.image66.Name = "image66";
			this.image66.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.62.png");
			this.button64.Add (this.image66);
			this.button64.Label = null;
			this.table1.Add (this.button64);
			global::Gtk.Table.TableChild w124 = ((global::Gtk.Table.TableChild)(this.table1 [this.button64]));
			w124.TopAttach = ((uint)(4));
			w124.BottomAttach = ((uint)(5));
			w124.LeftAttach = ((uint)(11));
			w124.RightAttach = ((uint)(12));
			w124.XOptions = ((global::Gtk.AttachOptions)(4));
			w124.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button65 = new global::Gtk.Button ();
			this.button65.CanFocus = true;
			this.button65.Name = "button65";
			// Container child button65.Gtk.Container+ContainerChild
			this.image67 = new global::Gtk.Image ();
			this.image67.Name = "image67";
			this.image67.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.63.png");
			this.button65.Add (this.image67);
			this.button65.Label = null;
			this.table1.Add (this.button65);
			global::Gtk.Table.TableChild w126 = ((global::Gtk.Table.TableChild)(this.table1 [this.button65]));
			w126.TopAttach = ((uint)(4));
			w126.BottomAttach = ((uint)(5));
			w126.LeftAttach = ((uint)(12));
			w126.RightAttach = ((uint)(13));
			w126.XOptions = ((global::Gtk.AttachOptions)(4));
			w126.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			// Container child button7.Gtk.Container+ContainerChild
			this.image10 = new global::Gtk.Image ();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.06.png");
			this.button7.Add (this.image10);
			this.button7.Label = null;
			this.table1.Add (this.button7);
			global::Gtk.Table.TableChild w128 = ((global::Gtk.Table.TableChild)(this.table1 [this.button7]));
			w128.LeftAttach = ((uint)(6));
			w128.RightAttach = ((uint)(7));
			w128.XOptions = ((global::Gtk.AttachOptions)(4));
			w128.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			// Container child button8.Gtk.Container+ContainerChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.07.png");
			this.button8.Add (this.image11);
			this.button8.Label = null;
			this.table1.Add (this.button8);
			global::Gtk.Table.TableChild w130 = ((global::Gtk.Table.TableChild)(this.table1 [this.button8]));
			w130.LeftAttach = ((uint)(7));
			w130.RightAttach = ((uint)(8));
			w130.XOptions = ((global::Gtk.AttachOptions)(4));
			w130.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			// Container child button9.Gtk.Container+ContainerChild
			this.image12 = new global::Gtk.Image ();
			this.image12.Name = "image12";
			this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleHack.GtkUI.Images.Symbols.08.png");
			this.button9.Add (this.image12);
			this.button9.Label = null;
			this.table1.Add (this.button9);
			global::Gtk.Table.TableChild w132 = ((global::Gtk.Table.TableChild)(this.table1 [this.button9]));
			w132.LeftAttach = ((uint)(8));
			w132.RightAttach = ((uint)(9));
			w132.XOptions = ((global::Gtk.AttachOptions)(4));
			w132.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w133.Position = 1;
			w133.Expand = false;
			w133.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.chkAppendRings = new global::Gtk.CheckButton ();
			this.chkAppendRings.CanFocus = true;
			this.chkAppendRings.Name = "chkAppendRings";
			this.chkAppendRings.Label = global::Mono.Unix.Catalog.GetString ("Add to Existing Rings");
			this.chkAppendRings.DrawIndicator = true;
			this.chkAppendRings.UseUnderline = true;
			this.hbox2.Add (this.chkAppendRings);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.chkAppendRings]));
			w134.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnDone = new global::Gtk.Button ();
			this.btnDone.CanFocus = true;
			this.btnDone.Name = "btnDone";
			this.btnDone.UseUnderline = true;
			this.btnDone.Label = global::Mono.Unix.Catalog.GetString ("Done");
			this.hbox2.Add (this.btnDone);
			global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnDone]));
			w135.Position = 2;
			w135.Expand = false;
			w135.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w136.Position = 2;
			w136.Expand = false;
			w136.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 338;
			this.DefaultHeight = 285;
			this.Show ();
			this.btnReset.Clicked += new global::System.EventHandler (this.OnBtnResetClicked);
			this.btnBack.Clicked += new global::System.EventHandler (this.OnBtnBackClicked);
			this.button9.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button8.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button7.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button65.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button64.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button63.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button62.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button61.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button60.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button6.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button59.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button58.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button57.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button56.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button55.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button54.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button53.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button52.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button51.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button50.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button5.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button49.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button48.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button47.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button46.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button45.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button44.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button43.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button42.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button41.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button40.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button39.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button38.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button37.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button36.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button35.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button33.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button32.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button31.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button30.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button29.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button28.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button27.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button26.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button25.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button24.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button23.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button22.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button21.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button20.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button19.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button18.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button17.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button16.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button15.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button14.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button13.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button12.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button11.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button10.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.button1.Clicked += new global::System.EventHandler (this.OnSymbolClicked);
			this.btnDone.Clicked += new global::System.EventHandler (this.OnBtnDoneClicked);
		}
	}
}
