
// This file has been generated by the GUI designer. Do not modify.
namespace Zyrenth.OracleGtk
{
	public partial class DecoderForm
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Table table3;
		private global::Gtk.Button btnBack;
		private global::Gtk.Button btnReset;
		private global::Gtk.Image img1;
		private global::Gtk.Image img10;
		private global::Gtk.Image img11;
		private global::Gtk.Image img12;
		private global::Gtk.Image img13;
		private global::Gtk.Image img14;
		private global::Gtk.Image img15;
		private global::Gtk.Image img16;
		private global::Gtk.Image img17;
		private global::Gtk.Image img18;
		private global::Gtk.Image img19;
		private global::Gtk.Image img2;
		private global::Gtk.Image img20;
		private global::Gtk.Image img3;
		private global::Gtk.Image img4;
		private global::Gtk.Image img5;
		private global::Gtk.Image img6;
		private global::Gtk.Image img7;
		private global::Gtk.Image img8;
		private global::Gtk.Image img9;
		private global::Gtk.Table table1;
		private global::Gtk.Button button1;
		private global::Gtk.Image image3;
		private global::Gtk.Button button10;
		private global::Gtk.Image image13;
		private global::Gtk.Button button11;
		private global::Gtk.Image image14;
		private global::Gtk.Button button12;
		private global::Gtk.Image image15;
		private global::Gtk.Button button13;
		private global::Gtk.Image image16;
		private global::Gtk.Button button14;
		private global::Gtk.Image image17;
		private global::Gtk.Button button15;
		private global::Gtk.Image image4;
		private global::Gtk.Button button16;
		private global::Gtk.Image image18;
		private global::Gtk.Button button17;
		private global::Gtk.Image image19;
		private global::Gtk.Button button18;
		private global::Gtk.Image image20;
		private global::Gtk.Button button19;
		private global::Gtk.Image image21;
		private global::Gtk.Button button2;
		private global::Gtk.Image image5;
		private global::Gtk.Button button20;
		private global::Gtk.Image image22;
		private global::Gtk.Button button21;
		private global::Gtk.Image image23;
		private global::Gtk.Button button22;
		private global::Gtk.Image image24;
		private global::Gtk.Button button23;
		private global::Gtk.Image image25;
		private global::Gtk.Button button24;
		private global::Gtk.Image image26;
		private global::Gtk.Button button25;
		private global::Gtk.Image image27;
		private global::Gtk.Button button26;
		private global::Gtk.Image image28;
		private global::Gtk.Button button27;
		private global::Gtk.Image image29;
		private global::Gtk.Button button28;
		private global::Gtk.Image image30;
		private global::Gtk.Button button29;
		private global::Gtk.Image image31;
		private global::Gtk.Button button3;
		private global::Gtk.Image image6;
		private global::Gtk.Button button30;
		private global::Gtk.Image image32;
		private global::Gtk.Button button31;
		private global::Gtk.Image image33;
		private global::Gtk.Button button32;
		private global::Gtk.Image image34;
		private global::Gtk.Button button33;
		private global::Gtk.Image image35;
		private global::Gtk.Button button35;
		private global::Gtk.Image image37;
		private global::Gtk.Button button36;
		private global::Gtk.Image image38;
		private global::Gtk.Button button37;
		private global::Gtk.Image image39;
		private global::Gtk.Button button38;
		private global::Gtk.Image image40;
		private global::Gtk.Button button39;
		private global::Gtk.Image image41;
		private global::Gtk.Button button4;
		private global::Gtk.Image image7;
		private global::Gtk.Button button40;
		private global::Gtk.Image image42;
		private global::Gtk.Button button41;
		private global::Gtk.Image image43;
		private global::Gtk.Button button42;
		private global::Gtk.Image image44;
		private global::Gtk.Button button43;
		private global::Gtk.Image image45;
		private global::Gtk.Button button44;
		private global::Gtk.Image image46;
		private global::Gtk.Button button45;
		private global::Gtk.Image image47;
		private global::Gtk.Button button46;
		private global::Gtk.Image image48;
		private global::Gtk.Button button47;
		private global::Gtk.Image image49;
		private global::Gtk.Button button48;
		private global::Gtk.Image image50;
		private global::Gtk.Button button49;
		private global::Gtk.Image image51;
		private global::Gtk.Button button5;
		private global::Gtk.Image image8;
		private global::Gtk.Button button50;
		private global::Gtk.Image image52;
		private global::Gtk.Button button51;
		private global::Gtk.Image image53;
		private global::Gtk.Button button52;
		private global::Gtk.Image image54;
		private global::Gtk.Button button53;
		private global::Gtk.Image image55;
		private global::Gtk.Button button54;
		private global::Gtk.Image image56;
		private global::Gtk.Button button55;
		private global::Gtk.Image image57;
		private global::Gtk.Button button56;
		private global::Gtk.Image image58;
		private global::Gtk.Button button57;
		private global::Gtk.Image image59;
		private global::Gtk.Button button58;
		private global::Gtk.Image image60;
		private global::Gtk.Button button59;
		private global::Gtk.Image image61;
		private global::Gtk.Button button6;
		private global::Gtk.Image image9;
		private global::Gtk.Button button60;
		private global::Gtk.Image image62;
		private global::Gtk.Button button61;
		private global::Gtk.Image image63;
		private global::Gtk.Button button62;
		private global::Gtk.Image image64;
		private global::Gtk.Button button63;
		private global::Gtk.Image image65;
		private global::Gtk.Button button64;
		private global::Gtk.Image image66;
		private global::Gtk.Button button65;
		private global::Gtk.Image image67;
		private global::Gtk.Button button7;
		private global::Gtk.Image image10;
		private global::Gtk.Button button8;
		private global::Gtk.Image image11;
		private global::Gtk.Button button9;
		private global::Gtk.Image image12;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Button button34;
		private global::Gtk.TextView textview1;
		private global::Gtk.TextView textview2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zyrenth.OracleGtk.DecoderForm
			this.Name = "Zyrenth.OracleGtk.DecoderForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("DecoderForm");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.Farore.gif");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Zyrenth.OracleGtk.DecoderForm.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(12)), false);
			this.table3.Name = "table3";
			// Container child table3.Gtk.Table+TableChild
			this.btnBack = new global::Gtk.Button ();
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString ("Back");
			this.table3.Add (this.btnBack);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnBack]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(11));
			w1.RightAttach = ((uint)(12));
			w1.XPadding = ((uint)(5));
			w1.YPadding = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.btnReset = new global::Gtk.Button ();
			this.btnReset.CanFocus = true;
			this.btnReset.Name = "btnReset";
			this.btnReset.UseUnderline = true;
			this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.table3.Add (this.btnReset);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.btnReset]));
			w2.LeftAttach = ((uint)(11));
			w2.RightAttach = ((uint)(12));
			w2.XPadding = ((uint)(5));
			w2.YPadding = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img1 = new global::Gtk.Image ();
			this.img1.WidthRequest = 16;
			this.img1.HeightRequest = 20;
			this.img1.Name = "img1";
			this.table3.Add (this.img1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.img1]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img10 = new global::Gtk.Image ();
			this.img10.WidthRequest = 16;
			this.img10.HeightRequest = 20;
			this.img10.Name = "img10";
			this.table3.Add (this.img10);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.img10]));
			w4.LeftAttach = ((uint)(10));
			w4.RightAttach = ((uint)(11));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img11 = new global::Gtk.Image ();
			this.img11.WidthRequest = 16;
			this.img11.HeightRequest = 20;
			this.img11.Name = "img11";
			this.table3.Add (this.img11);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.img11]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img12 = new global::Gtk.Image ();
			this.img12.WidthRequest = 16;
			this.img12.HeightRequest = 20;
			this.img12.Name = "img12";
			this.table3.Add (this.img12);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.img12]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img13 = new global::Gtk.Image ();
			this.img13.WidthRequest = 16;
			this.img13.HeightRequest = 20;
			this.img13.Name = "img13";
			this.table3.Add (this.img13);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.img13]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img14 = new global::Gtk.Image ();
			this.img14.WidthRequest = 16;
			this.img14.HeightRequest = 20;
			this.img14.Name = "img14";
			this.table3.Add (this.img14);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.img14]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(3));
			w8.RightAttach = ((uint)(4));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img15 = new global::Gtk.Image ();
			this.img15.WidthRequest = 16;
			this.img15.HeightRequest = 20;
			this.img15.Name = "img15";
			this.table3.Add (this.img15);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.img15]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(4));
			w9.RightAttach = ((uint)(5));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img16 = new global::Gtk.Image ();
			this.img16.WidthRequest = 16;
			this.img16.HeightRequest = 20;
			this.img16.Name = "img16";
			this.table3.Add (this.img16);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.img16]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(6));
			w10.RightAttach = ((uint)(7));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img17 = new global::Gtk.Image ();
			this.img17.WidthRequest = 16;
			this.img17.HeightRequest = 20;
			this.img17.Name = "img17";
			this.table3.Add (this.img17);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.img17]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(7));
			w11.RightAttach = ((uint)(8));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img18 = new global::Gtk.Image ();
			this.img18.WidthRequest = 16;
			this.img18.HeightRequest = 20;
			this.img18.Name = "img18";
			this.table3.Add (this.img18);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.img18]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(8));
			w12.RightAttach = ((uint)(9));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img19 = new global::Gtk.Image ();
			this.img19.WidthRequest = 16;
			this.img19.HeightRequest = 20;
			this.img19.Name = "img19";
			this.table3.Add (this.img19);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.img19]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(9));
			w13.RightAttach = ((uint)(10));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img2 = new global::Gtk.Image ();
			this.img2.WidthRequest = 16;
			this.img2.HeightRequest = 20;
			this.img2.Name = "img2";
			this.table3.Add (this.img2);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.img2]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img20 = new global::Gtk.Image ();
			this.img20.WidthRequest = 16;
			this.img20.HeightRequest = 20;
			this.img20.Name = "img20";
			this.table3.Add (this.img20);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.img20]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(10));
			w15.RightAttach = ((uint)(11));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img3 = new global::Gtk.Image ();
			this.img3.WidthRequest = 16;
			this.img3.HeightRequest = 20;
			this.img3.Name = "img3";
			this.table3.Add (this.img3);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.img3]));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img4 = new global::Gtk.Image ();
			this.img4.WidthRequest = 16;
			this.img4.HeightRequest = 20;
			this.img4.Name = "img4";
			this.table3.Add (this.img4);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.img4]));
			w17.LeftAttach = ((uint)(3));
			w17.RightAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img5 = new global::Gtk.Image ();
			this.img5.WidthRequest = 16;
			this.img5.HeightRequest = 20;
			this.img5.Name = "img5";
			this.table3.Add (this.img5);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.img5]));
			w18.LeftAttach = ((uint)(4));
			w18.RightAttach = ((uint)(5));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img6 = new global::Gtk.Image ();
			this.img6.WidthRequest = 16;
			this.img6.HeightRequest = 20;
			this.img6.Name = "img6";
			this.table3.Add (this.img6);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.img6]));
			w19.LeftAttach = ((uint)(6));
			w19.RightAttach = ((uint)(7));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img7 = new global::Gtk.Image ();
			this.img7.WidthRequest = 16;
			this.img7.HeightRequest = 20;
			this.img7.Name = "img7";
			this.table3.Add (this.img7);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.img7]));
			w20.LeftAttach = ((uint)(7));
			w20.RightAttach = ((uint)(8));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img8 = new global::Gtk.Image ();
			this.img8.WidthRequest = 16;
			this.img8.HeightRequest = 20;
			this.img8.Name = "img8";
			this.table3.Add (this.img8);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.img8]));
			w21.LeftAttach = ((uint)(8));
			w21.RightAttach = ((uint)(9));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.img9 = new global::Gtk.Image ();
			this.img9.WidthRequest = 16;
			this.img9.HeightRequest = 20;
			this.img9.Name = "img9";
			this.table3.Add (this.img9);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.img9]));
			w22.LeftAttach = ((uint)(9));
			w22.RightAttach = ((uint)(10));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table3]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(13)), false);
			this.table1.Name = "table1";
			// Container child table1.Gtk.Table+TableChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			// Container child button1.Gtk.Container+ContainerChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.00.png");
			this.button1.Add (this.image3);
			this.button1.Label = null;
			this.table1.Add (this.button1);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.button1]));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			// Container child button10.Gtk.Container+ContainerChild
			this.image13 = new global::Gtk.Image ();
			this.image13.Name = "image13";
			this.image13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.09.png");
			this.button10.Add (this.image13);
			this.button10.Label = null;
			this.table1.Add (this.button10);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.button10]));
			w27.LeftAttach = ((uint)(9));
			w27.RightAttach = ((uint)(10));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button11 = new global::Gtk.Button ();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			// Container child button11.Gtk.Container+ContainerChild
			this.image14 = new global::Gtk.Image ();
			this.image14.Name = "image14";
			this.image14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.10.png");
			this.button11.Add (this.image14);
			this.button11.Label = null;
			this.table1.Add (this.button11);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.button11]));
			w29.LeftAttach = ((uint)(10));
			w29.RightAttach = ((uint)(11));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button12 = new global::Gtk.Button ();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			// Container child button12.Gtk.Container+ContainerChild
			this.image15 = new global::Gtk.Image ();
			this.image15.Name = "image15";
			this.image15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.11.png");
			this.button12.Add (this.image15);
			this.button12.Label = null;
			this.table1.Add (this.button12);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.button12]));
			w31.LeftAttach = ((uint)(11));
			w31.RightAttach = ((uint)(12));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button13 = new global::Gtk.Button ();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			// Container child button13.Gtk.Container+ContainerChild
			this.image16 = new global::Gtk.Image ();
			this.image16.Name = "image16";
			this.image16.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.12.png");
			this.button13.Add (this.image16);
			this.button13.Label = null;
			this.table1.Add (this.button13);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.button13]));
			w33.LeftAttach = ((uint)(12));
			w33.RightAttach = ((uint)(13));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button14 = new global::Gtk.Button ();
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			// Container child button14.Gtk.Container+ContainerChild
			this.image17 = new global::Gtk.Image ();
			this.image17.Name = "image17";
			this.image17.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.13.png");
			this.button14.Add (this.image17);
			this.button14.Label = null;
			this.table1.Add (this.button14);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.button14]));
			w35.TopAttach = ((uint)(1));
			w35.BottomAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button15 = new global::Gtk.Button ();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			// Container child button15.Gtk.Container+ContainerChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.14.png");
			this.button15.Add (this.image4);
			this.button15.Label = null;
			this.table1.Add (this.button15);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1 [this.button15]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button16 = new global::Gtk.Button ();
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			// Container child button16.Gtk.Container+ContainerChild
			this.image18 = new global::Gtk.Image ();
			this.image18.Name = "image18";
			this.image18.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.15.png");
			this.button16.Add (this.image18);
			this.button16.Label = null;
			this.table1.Add (this.button16);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1 [this.button16]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(2));
			w39.RightAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button17 = new global::Gtk.Button ();
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			// Container child button17.Gtk.Container+ContainerChild
			this.image19 = new global::Gtk.Image ();
			this.image19.Name = "image19";
			this.image19.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.16.png");
			this.button17.Add (this.image19);
			this.button17.Label = null;
			this.table1.Add (this.button17);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table1 [this.button17]));
			w41.TopAttach = ((uint)(1));
			w41.BottomAttach = ((uint)(2));
			w41.LeftAttach = ((uint)(3));
			w41.RightAttach = ((uint)(4));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button18 = new global::Gtk.Button ();
			this.button18.CanFocus = true;
			this.button18.Name = "button18";
			// Container child button18.Gtk.Container+ContainerChild
			this.image20 = new global::Gtk.Image ();
			this.image20.Name = "image20";
			this.image20.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.17.png");
			this.button18.Add (this.image20);
			this.button18.Label = null;
			this.table1.Add (this.button18);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1 [this.button18]));
			w43.TopAttach = ((uint)(1));
			w43.BottomAttach = ((uint)(2));
			w43.LeftAttach = ((uint)(4));
			w43.RightAttach = ((uint)(5));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button19 = new global::Gtk.Button ();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			// Container child button19.Gtk.Container+ContainerChild
			this.image21 = new global::Gtk.Image ();
			this.image21.Name = "image21";
			this.image21.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.18.png");
			this.button19.Add (this.image21);
			this.button19.Label = null;
			this.table1.Add (this.button19);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1 [this.button19]));
			w45.TopAttach = ((uint)(1));
			w45.BottomAttach = ((uint)(2));
			w45.LeftAttach = ((uint)(5));
			w45.RightAttach = ((uint)(6));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			// Container child button2.Gtk.Container+ContainerChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.01.png");
			this.button2.Add (this.image5);
			this.button2.Label = null;
			this.table1.Add (this.button2);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1 [this.button2]));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button20 = new global::Gtk.Button ();
			this.button20.CanFocus = true;
			this.button20.Name = "button20";
			// Container child button20.Gtk.Container+ContainerChild
			this.image22 = new global::Gtk.Image ();
			this.image22.Name = "image22";
			this.image22.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.20.png");
			this.button20.Add (this.image22);
			this.button20.Label = null;
			this.table1.Add (this.button20);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1 [this.button20]));
			w49.TopAttach = ((uint)(1));
			w49.BottomAttach = ((uint)(2));
			w49.LeftAttach = ((uint)(7));
			w49.RightAttach = ((uint)(8));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button21 = new global::Gtk.Button ();
			this.button21.CanFocus = true;
			this.button21.Name = "button21";
			// Container child button21.Gtk.Container+ContainerChild
			this.image23 = new global::Gtk.Image ();
			this.image23.Name = "image23";
			this.image23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.19.png");
			this.button21.Add (this.image23);
			this.button21.Label = null;
			this.table1.Add (this.button21);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1 [this.button21]));
			w51.TopAttach = ((uint)(1));
			w51.BottomAttach = ((uint)(2));
			w51.LeftAttach = ((uint)(6));
			w51.RightAttach = ((uint)(7));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button22 = new global::Gtk.Button ();
			this.button22.CanFocus = true;
			this.button22.Name = "button22";
			// Container child button22.Gtk.Container+ContainerChild
			this.image24 = new global::Gtk.Image ();
			this.image24.Name = "image24";
			this.image24.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.21.png");
			this.button22.Add (this.image24);
			this.button22.Label = null;
			this.table1.Add (this.button22);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1 [this.button22]));
			w53.TopAttach = ((uint)(1));
			w53.BottomAttach = ((uint)(2));
			w53.LeftAttach = ((uint)(8));
			w53.RightAttach = ((uint)(9));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button23 = new global::Gtk.Button ();
			this.button23.CanFocus = true;
			this.button23.Name = "button23";
			// Container child button23.Gtk.Container+ContainerChild
			this.image25 = new global::Gtk.Image ();
			this.image25.Name = "image25";
			this.image25.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.22.png");
			this.button23.Add (this.image25);
			this.button23.Label = null;
			this.table1.Add (this.button23);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1 [this.button23]));
			w55.TopAttach = ((uint)(1));
			w55.BottomAttach = ((uint)(2));
			w55.LeftAttach = ((uint)(9));
			w55.RightAttach = ((uint)(10));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button24 = new global::Gtk.Button ();
			this.button24.CanFocus = true;
			this.button24.Name = "button24";
			// Container child button24.Gtk.Container+ContainerChild
			this.image26 = new global::Gtk.Image ();
			this.image26.Name = "image26";
			this.image26.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.23.png");
			this.button24.Add (this.image26);
			this.button24.Label = null;
			this.table1.Add (this.button24);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table1 [this.button24]));
			w57.TopAttach = ((uint)(1));
			w57.BottomAttach = ((uint)(2));
			w57.LeftAttach = ((uint)(10));
			w57.RightAttach = ((uint)(11));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button25 = new global::Gtk.Button ();
			this.button25.CanFocus = true;
			this.button25.Name = "button25";
			// Container child button25.Gtk.Container+ContainerChild
			this.image27 = new global::Gtk.Image ();
			this.image27.Name = "image27";
			this.image27.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.24.png");
			this.button25.Add (this.image27);
			this.button25.Label = null;
			this.table1.Add (this.button25);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table1 [this.button25]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(11));
			w59.RightAttach = ((uint)(12));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button26 = new global::Gtk.Button ();
			this.button26.CanFocus = true;
			this.button26.Name = "button26";
			// Container child button26.Gtk.Container+ContainerChild
			this.image28 = new global::Gtk.Image ();
			this.image28.Name = "image28";
			this.image28.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.25.png");
			this.button26.Add (this.image28);
			this.button26.Label = null;
			this.table1.Add (this.button26);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table1 [this.button26]));
			w61.TopAttach = ((uint)(1));
			w61.BottomAttach = ((uint)(2));
			w61.LeftAttach = ((uint)(12));
			w61.RightAttach = ((uint)(13));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button27 = new global::Gtk.Button ();
			this.button27.CanFocus = true;
			this.button27.Name = "button27";
			// Container child button27.Gtk.Container+ContainerChild
			this.image29 = new global::Gtk.Image ();
			this.image29.Name = "image29";
			this.image29.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.26.png");
			this.button27.Add (this.image29);
			this.button27.Label = null;
			this.table1.Add (this.button27);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table1 [this.button27]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button28 = new global::Gtk.Button ();
			this.button28.CanFocus = true;
			this.button28.Name = "button28";
			// Container child button28.Gtk.Container+ContainerChild
			this.image30 = new global::Gtk.Image ();
			this.image30.Name = "image30";
			this.image30.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.27.png");
			this.button28.Add (this.image30);
			this.button28.Label = null;
			this.table1.Add (this.button28);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table1 [this.button28]));
			w65.TopAttach = ((uint)(2));
			w65.BottomAttach = ((uint)(3));
			w65.LeftAttach = ((uint)(1));
			w65.RightAttach = ((uint)(2));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button29 = new global::Gtk.Button ();
			this.button29.CanFocus = true;
			this.button29.Name = "button29";
			// Container child button29.Gtk.Container+ContainerChild
			this.image31 = new global::Gtk.Image ();
			this.image31.Name = "image31";
			this.image31.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.28.png");
			this.button29.Add (this.image31);
			this.button29.Label = null;
			this.table1.Add (this.button29);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table1 [this.button29]));
			w67.TopAttach = ((uint)(2));
			w67.BottomAttach = ((uint)(3));
			w67.LeftAttach = ((uint)(2));
			w67.RightAttach = ((uint)(3));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			// Container child button3.Gtk.Container+ContainerChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.02.png");
			this.button3.Add (this.image6);
			this.button3.Label = null;
			this.table1.Add (this.button3);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table1 [this.button3]));
			w69.LeftAttach = ((uint)(2));
			w69.RightAttach = ((uint)(3));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button30 = new global::Gtk.Button ();
			this.button30.CanFocus = true;
			this.button30.Name = "button30";
			// Container child button30.Gtk.Container+ContainerChild
			this.image32 = new global::Gtk.Image ();
			this.image32.Name = "image32";
			this.image32.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.29.png");
			this.button30.Add (this.image32);
			this.button30.Label = null;
			this.table1.Add (this.button30);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table1 [this.button30]));
			w71.TopAttach = ((uint)(2));
			w71.BottomAttach = ((uint)(3));
			w71.LeftAttach = ((uint)(3));
			w71.RightAttach = ((uint)(4));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button31 = new global::Gtk.Button ();
			this.button31.CanFocus = true;
			this.button31.Name = "button31";
			// Container child button31.Gtk.Container+ContainerChild
			this.image33 = new global::Gtk.Image ();
			this.image33.Name = "image33";
			this.image33.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.30.png");
			this.button31.Add (this.image33);
			this.button31.Label = null;
			this.table1.Add (this.button31);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table1 [this.button31]));
			w73.TopAttach = ((uint)(2));
			w73.BottomAttach = ((uint)(3));
			w73.LeftAttach = ((uint)(4));
			w73.RightAttach = ((uint)(5));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button32 = new global::Gtk.Button ();
			this.button32.CanFocus = true;
			this.button32.Name = "button32";
			// Container child button32.Gtk.Container+ContainerChild
			this.image34 = new global::Gtk.Image ();
			this.image34.Name = "image34";
			this.image34.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.31.png");
			this.button32.Add (this.image34);
			this.button32.Label = null;
			this.table1.Add (this.button32);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table1 [this.button32]));
			w75.TopAttach = ((uint)(2));
			w75.BottomAttach = ((uint)(3));
			w75.LeftAttach = ((uint)(5));
			w75.RightAttach = ((uint)(6));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button33 = new global::Gtk.Button ();
			this.button33.CanFocus = true;
			this.button33.Name = "button33";
			// Container child button33.Gtk.Container+ContainerChild
			this.image35 = new global::Gtk.Image ();
			this.image35.Name = "image35";
			this.image35.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.32.png");
			this.button33.Add (this.image35);
			this.button33.Label = null;
			this.table1.Add (this.button33);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table1 [this.button33]));
			w77.TopAttach = ((uint)(2));
			w77.BottomAttach = ((uint)(3));
			w77.LeftAttach = ((uint)(7));
			w77.RightAttach = ((uint)(8));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button35 = new global::Gtk.Button ();
			this.button35.CanFocus = true;
			this.button35.Name = "button35";
			// Container child button35.Gtk.Container+ContainerChild
			this.image37 = new global::Gtk.Image ();
			this.image37.Name = "image37";
			this.image37.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.33.png");
			this.button35.Add (this.image37);
			this.button35.Label = null;
			this.table1.Add (this.button35);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table1 [this.button35]));
			w79.TopAttach = ((uint)(2));
			w79.BottomAttach = ((uint)(3));
			w79.LeftAttach = ((uint)(8));
			w79.RightAttach = ((uint)(9));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button36 = new global::Gtk.Button ();
			this.button36.CanFocus = true;
			this.button36.Name = "button36";
			// Container child button36.Gtk.Container+ContainerChild
			this.image38 = new global::Gtk.Image ();
			this.image38.Name = "image38";
			this.image38.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.34.png");
			this.button36.Add (this.image38);
			this.button36.Label = null;
			this.table1.Add (this.button36);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table1 [this.button36]));
			w81.TopAttach = ((uint)(2));
			w81.BottomAttach = ((uint)(3));
			w81.LeftAttach = ((uint)(9));
			w81.RightAttach = ((uint)(10));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button37 = new global::Gtk.Button ();
			this.button37.CanFocus = true;
			this.button37.Name = "button37";
			// Container child button37.Gtk.Container+ContainerChild
			this.image39 = new global::Gtk.Image ();
			this.image39.Name = "image39";
			this.image39.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.35.png");
			this.button37.Add (this.image39);
			this.button37.Label = null;
			this.table1.Add (this.button37);
			global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table1 [this.button37]));
			w83.TopAttach = ((uint)(2));
			w83.BottomAttach = ((uint)(3));
			w83.LeftAttach = ((uint)(10));
			w83.RightAttach = ((uint)(11));
			w83.XOptions = ((global::Gtk.AttachOptions)(4));
			w83.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button38 = new global::Gtk.Button ();
			this.button38.CanFocus = true;
			this.button38.Name = "button38";
			// Container child button38.Gtk.Container+ContainerChild
			this.image40 = new global::Gtk.Image ();
			this.image40.Name = "image40";
			this.image40.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.36.png");
			this.button38.Add (this.image40);
			this.button38.Label = null;
			this.table1.Add (this.button38);
			global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table1 [this.button38]));
			w85.TopAttach = ((uint)(2));
			w85.BottomAttach = ((uint)(3));
			w85.LeftAttach = ((uint)(11));
			w85.RightAttach = ((uint)(12));
			w85.XOptions = ((global::Gtk.AttachOptions)(4));
			w85.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button39 = new global::Gtk.Button ();
			this.button39.CanFocus = true;
			this.button39.Name = "button39";
			// Container child button39.Gtk.Container+ContainerChild
			this.image41 = new global::Gtk.Image ();
			this.image41.Name = "image41";
			this.image41.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.37.png");
			this.button39.Add (this.image41);
			this.button39.Label = null;
			this.table1.Add (this.button39);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table1 [this.button39]));
			w87.TopAttach = ((uint)(2));
			w87.BottomAttach = ((uint)(3));
			w87.LeftAttach = ((uint)(12));
			w87.RightAttach = ((uint)(13));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			w87.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			// Container child button4.Gtk.Container+ContainerChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.03.png");
			this.button4.Add (this.image7);
			this.button4.Label = null;
			this.table1.Add (this.button4);
			global::Gtk.Table.TableChild w89 = ((global::Gtk.Table.TableChild)(this.table1 [this.button4]));
			w89.LeftAttach = ((uint)(3));
			w89.RightAttach = ((uint)(4));
			w89.XOptions = ((global::Gtk.AttachOptions)(4));
			w89.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button40 = new global::Gtk.Button ();
			this.button40.CanFocus = true;
			this.button40.Name = "button40";
			// Container child button40.Gtk.Container+ContainerChild
			this.image42 = new global::Gtk.Image ();
			this.image42.Name = "image42";
			this.image42.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.38.png");
			this.button40.Add (this.image42);
			this.button40.Label = null;
			this.table1.Add (this.button40);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table1 [this.button40]));
			w91.TopAttach = ((uint)(3));
			w91.BottomAttach = ((uint)(4));
			w91.XOptions = ((global::Gtk.AttachOptions)(4));
			w91.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button41 = new global::Gtk.Button ();
			this.button41.CanFocus = true;
			this.button41.Name = "button41";
			// Container child button41.Gtk.Container+ContainerChild
			this.image43 = new global::Gtk.Image ();
			this.image43.Name = "image43";
			this.image43.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.39.png");
			this.button41.Add (this.image43);
			this.button41.Label = null;
			this.table1.Add (this.button41);
			global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.table1 [this.button41]));
			w93.TopAttach = ((uint)(3));
			w93.BottomAttach = ((uint)(4));
			w93.LeftAttach = ((uint)(1));
			w93.RightAttach = ((uint)(2));
			w93.XOptions = ((global::Gtk.AttachOptions)(4));
			w93.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button42 = new global::Gtk.Button ();
			this.button42.CanFocus = true;
			this.button42.Name = "button42";
			// Container child button42.Gtk.Container+ContainerChild
			this.image44 = new global::Gtk.Image ();
			this.image44.Name = "image44";
			this.image44.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.40.png");
			this.button42.Add (this.image44);
			this.button42.Label = null;
			this.table1.Add (this.button42);
			global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.table1 [this.button42]));
			w95.TopAttach = ((uint)(3));
			w95.BottomAttach = ((uint)(4));
			w95.LeftAttach = ((uint)(2));
			w95.RightAttach = ((uint)(3));
			w95.XOptions = ((global::Gtk.AttachOptions)(4));
			w95.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button43 = new global::Gtk.Button ();
			this.button43.CanFocus = true;
			this.button43.Name = "button43";
			// Container child button43.Gtk.Container+ContainerChild
			this.image45 = new global::Gtk.Image ();
			this.image45.Name = "image45";
			this.image45.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.41.png");
			this.button43.Add (this.image45);
			this.button43.Label = null;
			this.table1.Add (this.button43);
			global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.table1 [this.button43]));
			w97.TopAttach = ((uint)(3));
			w97.BottomAttach = ((uint)(4));
			w97.LeftAttach = ((uint)(3));
			w97.RightAttach = ((uint)(4));
			w97.XOptions = ((global::Gtk.AttachOptions)(4));
			w97.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button44 = new global::Gtk.Button ();
			this.button44.CanFocus = true;
			this.button44.Name = "button44";
			// Container child button44.Gtk.Container+ContainerChild
			this.image46 = new global::Gtk.Image ();
			this.image46.Name = "image46";
			this.image46.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.42.png");
			this.button44.Add (this.image46);
			this.button44.Label = null;
			this.table1.Add (this.button44);
			global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.table1 [this.button44]));
			w99.TopAttach = ((uint)(3));
			w99.BottomAttach = ((uint)(4));
			w99.LeftAttach = ((uint)(4));
			w99.RightAttach = ((uint)(5));
			w99.XOptions = ((global::Gtk.AttachOptions)(4));
			w99.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button45 = new global::Gtk.Button ();
			this.button45.CanFocus = true;
			this.button45.Name = "button45";
			// Container child button45.Gtk.Container+ContainerChild
			this.image47 = new global::Gtk.Image ();
			this.image47.Name = "image47";
			this.image47.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.43.png");
			this.button45.Add (this.image47);
			this.button45.Label = null;
			this.table1.Add (this.button45);
			global::Gtk.Table.TableChild w101 = ((global::Gtk.Table.TableChild)(this.table1 [this.button45]));
			w101.TopAttach = ((uint)(3));
			w101.BottomAttach = ((uint)(4));
			w101.LeftAttach = ((uint)(5));
			w101.RightAttach = ((uint)(6));
			w101.XOptions = ((global::Gtk.AttachOptions)(4));
			w101.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button46 = new global::Gtk.Button ();
			this.button46.CanFocus = true;
			this.button46.Name = "button46";
			// Container child button46.Gtk.Container+ContainerChild
			this.image48 = new global::Gtk.Image ();
			this.image48.Name = "image48";
			this.image48.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.44.png");
			this.button46.Add (this.image48);
			this.button46.Label = null;
			this.table1.Add (this.button46);
			global::Gtk.Table.TableChild w103 = ((global::Gtk.Table.TableChild)(this.table1 [this.button46]));
			w103.TopAttach = ((uint)(3));
			w103.BottomAttach = ((uint)(4));
			w103.LeftAttach = ((uint)(6));
			w103.RightAttach = ((uint)(7));
			w103.XOptions = ((global::Gtk.AttachOptions)(4));
			w103.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button47 = new global::Gtk.Button ();
			this.button47.CanFocus = true;
			this.button47.Name = "button47";
			// Container child button47.Gtk.Container+ContainerChild
			this.image49 = new global::Gtk.Image ();
			this.image49.Name = "image49";
			this.image49.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.45.png");
			this.button47.Add (this.image49);
			this.button47.Label = null;
			this.table1.Add (this.button47);
			global::Gtk.Table.TableChild w105 = ((global::Gtk.Table.TableChild)(this.table1 [this.button47]));
			w105.TopAttach = ((uint)(3));
			w105.BottomAttach = ((uint)(4));
			w105.LeftAttach = ((uint)(7));
			w105.RightAttach = ((uint)(8));
			w105.XOptions = ((global::Gtk.AttachOptions)(4));
			w105.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button48 = new global::Gtk.Button ();
			this.button48.CanFocus = true;
			this.button48.Name = "button48";
			// Container child button48.Gtk.Container+ContainerChild
			this.image50 = new global::Gtk.Image ();
			this.image50.Name = "image50";
			this.image50.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.46.png");
			this.button48.Add (this.image50);
			this.button48.Label = null;
			this.table1.Add (this.button48);
			global::Gtk.Table.TableChild w107 = ((global::Gtk.Table.TableChild)(this.table1 [this.button48]));
			w107.TopAttach = ((uint)(3));
			w107.BottomAttach = ((uint)(4));
			w107.LeftAttach = ((uint)(8));
			w107.RightAttach = ((uint)(9));
			w107.XOptions = ((global::Gtk.AttachOptions)(4));
			w107.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button49 = new global::Gtk.Button ();
			this.button49.CanFocus = true;
			this.button49.Name = "button49";
			// Container child button49.Gtk.Container+ContainerChild
			this.image51 = new global::Gtk.Image ();
			this.image51.Name = "image51";
			this.image51.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.47.png");
			this.button49.Add (this.image51);
			this.button49.Label = null;
			this.table1.Add (this.button49);
			global::Gtk.Table.TableChild w109 = ((global::Gtk.Table.TableChild)(this.table1 [this.button49]));
			w109.TopAttach = ((uint)(3));
			w109.BottomAttach = ((uint)(4));
			w109.LeftAttach = ((uint)(9));
			w109.RightAttach = ((uint)(10));
			w109.XOptions = ((global::Gtk.AttachOptions)(4));
			w109.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			// Container child button5.Gtk.Container+ContainerChild
			this.image8 = new global::Gtk.Image ();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.04.png");
			this.button5.Add (this.image8);
			this.button5.Label = null;
			this.table1.Add (this.button5);
			global::Gtk.Table.TableChild w111 = ((global::Gtk.Table.TableChild)(this.table1 [this.button5]));
			w111.LeftAttach = ((uint)(4));
			w111.RightAttach = ((uint)(5));
			w111.XOptions = ((global::Gtk.AttachOptions)(4));
			w111.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button50 = new global::Gtk.Button ();
			this.button50.CanFocus = true;
			this.button50.Name = "button50";
			// Container child button50.Gtk.Container+ContainerChild
			this.image52 = new global::Gtk.Image ();
			this.image52.Name = "image52";
			this.image52.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.48.png");
			this.button50.Add (this.image52);
			this.button50.Label = null;
			this.table1.Add (this.button50);
			global::Gtk.Table.TableChild w113 = ((global::Gtk.Table.TableChild)(this.table1 [this.button50]));
			w113.TopAttach = ((uint)(3));
			w113.BottomAttach = ((uint)(4));
			w113.LeftAttach = ((uint)(10));
			w113.RightAttach = ((uint)(11));
			w113.XOptions = ((global::Gtk.AttachOptions)(4));
			w113.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button51 = new global::Gtk.Button ();
			this.button51.CanFocus = true;
			this.button51.Name = "button51";
			// Container child button51.Gtk.Container+ContainerChild
			this.image53 = new global::Gtk.Image ();
			this.image53.Name = "image53";
			this.image53.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.49.png");
			this.button51.Add (this.image53);
			this.button51.Label = null;
			this.table1.Add (this.button51);
			global::Gtk.Table.TableChild w115 = ((global::Gtk.Table.TableChild)(this.table1 [this.button51]));
			w115.TopAttach = ((uint)(3));
			w115.BottomAttach = ((uint)(4));
			w115.LeftAttach = ((uint)(11));
			w115.RightAttach = ((uint)(12));
			w115.XOptions = ((global::Gtk.AttachOptions)(4));
			w115.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button52 = new global::Gtk.Button ();
			this.button52.CanFocus = true;
			this.button52.Name = "button52";
			// Container child button52.Gtk.Container+ContainerChild
			this.image54 = new global::Gtk.Image ();
			this.image54.Name = "image54";
			this.image54.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.50.png");
			this.button52.Add (this.image54);
			this.button52.Label = null;
			this.table1.Add (this.button52);
			global::Gtk.Table.TableChild w117 = ((global::Gtk.Table.TableChild)(this.table1 [this.button52]));
			w117.TopAttach = ((uint)(3));
			w117.BottomAttach = ((uint)(4));
			w117.LeftAttach = ((uint)(12));
			w117.RightAttach = ((uint)(13));
			w117.XOptions = ((global::Gtk.AttachOptions)(4));
			w117.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button53 = new global::Gtk.Button ();
			this.button53.CanFocus = true;
			this.button53.Name = "button53";
			// Container child button53.Gtk.Container+ContainerChild
			this.image55 = new global::Gtk.Image ();
			this.image55.Name = "image55";
			this.image55.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.51.png");
			this.button53.Add (this.image55);
			this.button53.Label = null;
			this.table1.Add (this.button53);
			global::Gtk.Table.TableChild w119 = ((global::Gtk.Table.TableChild)(this.table1 [this.button53]));
			w119.TopAttach = ((uint)(4));
			w119.BottomAttach = ((uint)(5));
			w119.XOptions = ((global::Gtk.AttachOptions)(4));
			w119.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button54 = new global::Gtk.Button ();
			this.button54.CanFocus = true;
			this.button54.Name = "button54";
			// Container child button54.Gtk.Container+ContainerChild
			this.image56 = new global::Gtk.Image ();
			this.image56.Name = "image56";
			this.image56.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.52.png");
			this.button54.Add (this.image56);
			this.button54.Label = null;
			this.table1.Add (this.button54);
			global::Gtk.Table.TableChild w121 = ((global::Gtk.Table.TableChild)(this.table1 [this.button54]));
			w121.TopAttach = ((uint)(4));
			w121.BottomAttach = ((uint)(5));
			w121.LeftAttach = ((uint)(1));
			w121.RightAttach = ((uint)(2));
			w121.XOptions = ((global::Gtk.AttachOptions)(4));
			w121.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button55 = new global::Gtk.Button ();
			this.button55.CanFocus = true;
			this.button55.Name = "button55";
			// Container child button55.Gtk.Container+ContainerChild
			this.image57 = new global::Gtk.Image ();
			this.image57.Name = "image57";
			this.image57.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.53.png");
			this.button55.Add (this.image57);
			this.button55.Label = null;
			this.table1.Add (this.button55);
			global::Gtk.Table.TableChild w123 = ((global::Gtk.Table.TableChild)(this.table1 [this.button55]));
			w123.TopAttach = ((uint)(4));
			w123.BottomAttach = ((uint)(5));
			w123.LeftAttach = ((uint)(2));
			w123.RightAttach = ((uint)(3));
			w123.XOptions = ((global::Gtk.AttachOptions)(4));
			w123.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button56 = new global::Gtk.Button ();
			this.button56.CanFocus = true;
			this.button56.Name = "button56";
			// Container child button56.Gtk.Container+ContainerChild
			this.image58 = new global::Gtk.Image ();
			this.image58.Name = "image58";
			this.image58.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.54.png");
			this.button56.Add (this.image58);
			this.button56.Label = null;
			this.table1.Add (this.button56);
			global::Gtk.Table.TableChild w125 = ((global::Gtk.Table.TableChild)(this.table1 [this.button56]));
			w125.TopAttach = ((uint)(4));
			w125.BottomAttach = ((uint)(5));
			w125.LeftAttach = ((uint)(3));
			w125.RightAttach = ((uint)(4));
			w125.XOptions = ((global::Gtk.AttachOptions)(4));
			w125.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button57 = new global::Gtk.Button ();
			this.button57.CanFocus = true;
			this.button57.Name = "button57";
			// Container child button57.Gtk.Container+ContainerChild
			this.image59 = new global::Gtk.Image ();
			this.image59.Name = "image59";
			this.image59.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.55.png");
			this.button57.Add (this.image59);
			this.button57.Label = null;
			this.table1.Add (this.button57);
			global::Gtk.Table.TableChild w127 = ((global::Gtk.Table.TableChild)(this.table1 [this.button57]));
			w127.TopAttach = ((uint)(4));
			w127.BottomAttach = ((uint)(5));
			w127.LeftAttach = ((uint)(4));
			w127.RightAttach = ((uint)(5));
			w127.XOptions = ((global::Gtk.AttachOptions)(4));
			w127.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button58 = new global::Gtk.Button ();
			this.button58.CanFocus = true;
			this.button58.Name = "button58";
			// Container child button58.Gtk.Container+ContainerChild
			this.image60 = new global::Gtk.Image ();
			this.image60.Name = "image60";
			this.image60.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.56.png");
			this.button58.Add (this.image60);
			this.button58.Label = null;
			this.table1.Add (this.button58);
			global::Gtk.Table.TableChild w129 = ((global::Gtk.Table.TableChild)(this.table1 [this.button58]));
			w129.TopAttach = ((uint)(4));
			w129.BottomAttach = ((uint)(5));
			w129.LeftAttach = ((uint)(5));
			w129.RightAttach = ((uint)(6));
			w129.XOptions = ((global::Gtk.AttachOptions)(4));
			w129.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button59 = new global::Gtk.Button ();
			this.button59.CanFocus = true;
			this.button59.Name = "button59";
			// Container child button59.Gtk.Container+ContainerChild
			this.image61 = new global::Gtk.Image ();
			this.image61.Name = "image61";
			this.image61.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.57.png");
			this.button59.Add (this.image61);
			this.button59.Label = null;
			this.table1.Add (this.button59);
			global::Gtk.Table.TableChild w131 = ((global::Gtk.Table.TableChild)(this.table1 [this.button59]));
			w131.TopAttach = ((uint)(4));
			w131.BottomAttach = ((uint)(5));
			w131.LeftAttach = ((uint)(6));
			w131.RightAttach = ((uint)(7));
			w131.XOptions = ((global::Gtk.AttachOptions)(4));
			w131.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			// Container child button6.Gtk.Container+ContainerChild
			this.image9 = new global::Gtk.Image ();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.05.png");
			this.button6.Add (this.image9);
			this.button6.Label = null;
			this.table1.Add (this.button6);
			global::Gtk.Table.TableChild w133 = ((global::Gtk.Table.TableChild)(this.table1 [this.button6]));
			w133.LeftAttach = ((uint)(5));
			w133.RightAttach = ((uint)(6));
			w133.XOptions = ((global::Gtk.AttachOptions)(4));
			w133.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button60 = new global::Gtk.Button ();
			this.button60.CanFocus = true;
			this.button60.Name = "button60";
			// Container child button60.Gtk.Container+ContainerChild
			this.image62 = new global::Gtk.Image ();
			this.image62.Name = "image62";
			this.image62.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.58.png");
			this.button60.Add (this.image62);
			this.button60.Label = null;
			this.table1.Add (this.button60);
			global::Gtk.Table.TableChild w135 = ((global::Gtk.Table.TableChild)(this.table1 [this.button60]));
			w135.TopAttach = ((uint)(4));
			w135.BottomAttach = ((uint)(5));
			w135.LeftAttach = ((uint)(7));
			w135.RightAttach = ((uint)(8));
			w135.XOptions = ((global::Gtk.AttachOptions)(4));
			w135.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button61 = new global::Gtk.Button ();
			this.button61.CanFocus = true;
			this.button61.Name = "button61";
			// Container child button61.Gtk.Container+ContainerChild
			this.image63 = new global::Gtk.Image ();
			this.image63.Name = "image63";
			this.image63.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.59.png");
			this.button61.Add (this.image63);
			this.button61.Label = null;
			this.table1.Add (this.button61);
			global::Gtk.Table.TableChild w137 = ((global::Gtk.Table.TableChild)(this.table1 [this.button61]));
			w137.TopAttach = ((uint)(4));
			w137.BottomAttach = ((uint)(5));
			w137.LeftAttach = ((uint)(8));
			w137.RightAttach = ((uint)(9));
			w137.XOptions = ((global::Gtk.AttachOptions)(4));
			w137.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button62 = new global::Gtk.Button ();
			this.button62.CanFocus = true;
			this.button62.Name = "button62";
			// Container child button62.Gtk.Container+ContainerChild
			this.image64 = new global::Gtk.Image ();
			this.image64.Name = "image64";
			this.image64.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.60.png");
			this.button62.Add (this.image64);
			this.button62.Label = null;
			this.table1.Add (this.button62);
			global::Gtk.Table.TableChild w139 = ((global::Gtk.Table.TableChild)(this.table1 [this.button62]));
			w139.TopAttach = ((uint)(4));
			w139.BottomAttach = ((uint)(5));
			w139.LeftAttach = ((uint)(9));
			w139.RightAttach = ((uint)(10));
			w139.XOptions = ((global::Gtk.AttachOptions)(4));
			w139.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button63 = new global::Gtk.Button ();
			this.button63.CanFocus = true;
			this.button63.Name = "button63";
			// Container child button63.Gtk.Container+ContainerChild
			this.image65 = new global::Gtk.Image ();
			this.image65.Name = "image65";
			this.image65.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.61.png");
			this.button63.Add (this.image65);
			this.button63.Label = null;
			this.table1.Add (this.button63);
			global::Gtk.Table.TableChild w141 = ((global::Gtk.Table.TableChild)(this.table1 [this.button63]));
			w141.TopAttach = ((uint)(4));
			w141.BottomAttach = ((uint)(5));
			w141.LeftAttach = ((uint)(10));
			w141.RightAttach = ((uint)(11));
			w141.XOptions = ((global::Gtk.AttachOptions)(4));
			w141.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button64 = new global::Gtk.Button ();
			this.button64.CanFocus = true;
			this.button64.Name = "button64";
			// Container child button64.Gtk.Container+ContainerChild
			this.image66 = new global::Gtk.Image ();
			this.image66.Name = "image66";
			this.image66.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.62.png");
			this.button64.Add (this.image66);
			this.button64.Label = null;
			this.table1.Add (this.button64);
			global::Gtk.Table.TableChild w143 = ((global::Gtk.Table.TableChild)(this.table1 [this.button64]));
			w143.TopAttach = ((uint)(4));
			w143.BottomAttach = ((uint)(5));
			w143.LeftAttach = ((uint)(11));
			w143.RightAttach = ((uint)(12));
			w143.XOptions = ((global::Gtk.AttachOptions)(4));
			w143.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button65 = new global::Gtk.Button ();
			this.button65.CanFocus = true;
			this.button65.Name = "button65";
			// Container child button65.Gtk.Container+ContainerChild
			this.image67 = new global::Gtk.Image ();
			this.image67.Name = "image67";
			this.image67.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.63.png");
			this.button65.Add (this.image67);
			this.button65.Label = null;
			this.table1.Add (this.button65);
			global::Gtk.Table.TableChild w145 = ((global::Gtk.Table.TableChild)(this.table1 [this.button65]));
			w145.TopAttach = ((uint)(4));
			w145.BottomAttach = ((uint)(5));
			w145.LeftAttach = ((uint)(12));
			w145.RightAttach = ((uint)(13));
			w145.XOptions = ((global::Gtk.AttachOptions)(4));
			w145.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			// Container child button7.Gtk.Container+ContainerChild
			this.image10 = new global::Gtk.Image ();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.06.png");
			this.button7.Add (this.image10);
			this.button7.Label = null;
			this.table1.Add (this.button7);
			global::Gtk.Table.TableChild w147 = ((global::Gtk.Table.TableChild)(this.table1 [this.button7]));
			w147.LeftAttach = ((uint)(6));
			w147.RightAttach = ((uint)(7));
			w147.XOptions = ((global::Gtk.AttachOptions)(4));
			w147.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			// Container child button8.Gtk.Container+ContainerChild
			this.image11 = new global::Gtk.Image ();
			this.image11.Name = "image11";
			this.image11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.07.png");
			this.button8.Add (this.image11);
			this.button8.Label = null;
			this.table1.Add (this.button8);
			global::Gtk.Table.TableChild w149 = ((global::Gtk.Table.TableChild)(this.table1 [this.button8]));
			w149.LeftAttach = ((uint)(7));
			w149.RightAttach = ((uint)(8));
			w149.XOptions = ((global::Gtk.AttachOptions)(4));
			w149.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			// Container child button9.Gtk.Container+ContainerChild
			this.image12 = new global::Gtk.Image ();
			this.image12.Name = "image12";
			this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Zyrenth.OracleGtk.Resources.08.png");
			this.button9.Add (this.image12);
			this.button9.Label = null;
			this.table1.Add (this.button9);
			global::Gtk.Table.TableChild w151 = ((global::Gtk.Table.TableChild)(this.table1 [this.button9]));
			w151.LeftAttach = ((uint)(8));
			w151.RightAttach = ((uint)(9));
			w151.XOptions = ((global::Gtk.AttachOptions)(4));
			w151.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w152 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w152.Position = 2;
			w152.Expand = false;
			w152.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w153 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w153.Position = 0;
			w153.Expand = false;
			w153.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button34 = new global::Gtk.Button ();
			this.button34.CanFocus = true;
			this.button34.Name = "button34";
			this.button34.UseUnderline = true;
			this.button34.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.vbox3.Add (this.button34);
			global::Gtk.Box.BoxChild w154 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button34]));
			w154.Position = 0;
			w154.Expand = false;
			w154.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(1));
			this.vbox3.Add (this.textview1);
			global::Gtk.Box.BoxChild w155 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.textview1]));
			w155.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.textview2.WrapMode = ((global::Gtk.WrapMode)(1));
			this.vbox3.Add (this.textview2);
			global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.textview2]));
			w156.Position = 2;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w157 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w157.Position = 1;
			w157.Expand = false;
			w157.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 644;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
